// Generated by scripts/cpu_matrix.py -- timing harness only.
module fmax_top (
  input  wire clk,
  input  wire rst,
  input  wire din,
  output wire dout
);
  reg [174:0] stim;
  wire [224:0] obs;
  reg [224:0] obs_r;
  always @(posedge clk) stim <= {stim[173:0], din};
  always @(posedge clk) obs_r <= obs;
  reg [14:0] red;
  always @(posedge clk) red[0] <= ^obs_r[15:0];
  always @(posedge clk) red[1] <= ^obs_r[31:16];
  always @(posedge clk) red[2] <= ^obs_r[47:32];
  always @(posedge clk) red[3] <= ^obs_r[63:48];
  always @(posedge clk) red[4] <= ^obs_r[79:64];
  always @(posedge clk) red[5] <= ^obs_r[95:80];
  always @(posedge clk) red[6] <= ^obs_r[111:96];
  always @(posedge clk) red[7] <= ^obs_r[127:112];
  always @(posedge clk) red[8] <= ^obs_r[143:128];
  always @(posedge clk) red[9] <= ^obs_r[159:144];
  always @(posedge clk) red[10] <= ^obs_r[175:160];
  always @(posedge clk) red[11] <= ^obs_r[191:176];
  always @(posedge clk) red[12] <= ^obs_r[207:192];
  always @(posedge clk) red[13] <= ^obs_r[223:208];
  always @(posedge clk) red[14] <= ^obs_r[224:224];
  reg dout_r;
  always @(posedge clk) dout_r <= ^red;
  assign dout = dout_r;
  VexiiRiscv dut (
    .clk(clk),
    .reset(rst),
    .FetchL1Plugin_logic_bus_cmd_ready(stim[0]),
    .FetchL1Plugin_logic_bus_rsp_valid(stim[1]),
    .FetchL1Plugin_logic_bus_rsp_payload_data(stim[33:2]),
    .FetchL1Plugin_logic_bus_rsp_payload_error(stim[34]),
    .LsuL1Plugin_logic_bus_read_cmd_ready(stim[35]),
    .LsuL1Plugin_logic_bus_read_rsp_valid(stim[36]),
    .LsuL1Plugin_logic_bus_read_rsp_payload_data(stim[68:37]),
    .LsuL1Plugin_logic_bus_read_rsp_payload_error(stim[69]),
    .LsuL1Plugin_logic_bus_write_cmd_ready(stim[70]),
    .LsuL1Plugin_logic_bus_write_rsp_valid(stim[71]),
    .LsuL1Plugin_logic_bus_write_rsp_payload_error(stim[72]),
    .PrivilegedPlugin_logic_rdtime(stim[136:73]),
    .PrivilegedPlugin_logic_harts_0_int_m_timer(stim[137]),
    .PrivilegedPlugin_logic_harts_0_int_m_software(stim[138]),
    .PrivilegedPlugin_logic_harts_0_int_m_external(stim[139]),
    .LsuPlugin_logic_bus_cmd_ready(stim[140]),
    .LsuPlugin_logic_bus_rsp_valid(stim[141]),
    .LsuPlugin_logic_bus_rsp_payload_error(stim[142]),
    .LsuPlugin_logic_bus_rsp_payload_data(stim[174:143]),
    .FetchL1Plugin_logic_bus_cmd_valid(obs[0]),
    .FetchL1Plugin_logic_bus_cmd_payload_address(obs[32:1]),
    .FetchL1Plugin_logic_bus_cmd_payload_io(obs[33]),
    .FetchL1Plugin_logic_bus_rsp_ready(obs[34]),
    .LsuL1Plugin_logic_bus_read_cmd_valid(obs[35]),
    .LsuL1Plugin_logic_bus_read_cmd_payload_address(obs[67:36]),
    .LsuL1Plugin_logic_bus_read_rsp_ready(obs[68]),
    .LsuL1Plugin_logic_bus_write_cmd_valid(obs[69]),
    .LsuL1Plugin_logic_bus_write_cmd_payload_last(obs[70]),
    .LsuL1Plugin_logic_bus_write_cmd_payload_fragment_address(obs[102:71]),
    .LsuL1Plugin_logic_bus_write_cmd_payload_fragment_data(obs[134:103]),
    .LsuPlugin_logic_bus_cmd_valid(obs[135]),
    .LsuPlugin_logic_bus_cmd_payload_write(obs[136]),
    .LsuPlugin_logic_bus_cmd_payload_address(obs[168:137]),
    .LsuPlugin_logic_bus_cmd_payload_data(obs[200:169]),
    .LsuPlugin_logic_bus_cmd_payload_size(obs[202:201]),
    .LsuPlugin_logic_bus_cmd_payload_mask(obs[206:203]),
    .LsuPlugin_logic_bus_cmd_payload_io(obs[207]),
    .LsuPlugin_logic_bus_cmd_payload_fromHart(obs[208]),
    .LsuPlugin_logic_bus_cmd_payload_uopId(obs[224:209])
  );
endmodule
