#!/bin/sh
# Automatically generated by Amaranth 0.5.9. Do not edit.
set -e
[ -n "$AMARANTH_ENV_TRELLIS" ] && . "$AMARANTH_ENV_TRELLIS"
: ${YOSYS:=yosys}
: ${NEXTPNR_ECP5:=nextpnr-ecp5}
: ${ECPPACK:=ecppack}
"$YOSYS" -q -l top.rpt top.ys
"$NEXTPNR_ECP5" --quiet --log top.tim --12k --package CABGA256 --speed 8 --json top.json --lpf top.lpf --textcfg top.config
"$ECPPACK" --compress --freq 38.8 --input top.config --bit top.bit --svf top.svf
