// Choose which variant constants `base.rs` includes. Generated by
// `scripts/soc_generate_pac.py`; do not edit.
//
// `CYNTHION_SOC_VARIANT_RS` is written per variant by `soc_run.py` into that
// variant's build directory (#480). Unset is the committed default rung.
use std::path::PathBuf;

fn main() {
    let src = match std::env::var_os("CYNTHION_SOC_VARIANT_RS") {
        Some(path) => PathBuf::from(path),
        None => PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("src/variant.rs"),
    };
    let text = std::fs::read_to_string(&src)
        .unwrap_or_else(|e| panic!("variant constants {}: {e}", src.display()));
    let out = PathBuf::from(std::env::var_os("OUT_DIR").unwrap()).join("variant.rs");
    std::fs::write(&out, text).expect("writing variant.rs into OUT_DIR");

    println!("cargo:rerun-if-env-changed=CYNTHION_SOC_VARIANT_RS");
    println!("cargo:rerun-if-changed={}", src.display());
}
