//! What tree this image was built from, and when, written into the binary.
//!
//! `src/info.rs` includes the file this writes. Nothing else in the firmware may
//! depend on it: the shell reports provenance and never behaves differently
//! because of it.
//!
//! ## The dirty bit is the load-bearing field
//!
//! A hash names a commit. An image built from a modified tree is not that
//! commit, and reporting the hash alone would be a claim nobody could check --
//! which is worse than reporting nothing, because it looks like an answer.
//!
//! ## The encoding is `gateware/build_helpers.py`'s, deliberately
//!
//! `usercode()` there stamps the ECP5's USERCODE with `short=7 & 0x7fffffff`,
//! and sets bit 31 when `git status --porcelain` says anything. The gateware's
//! `gateware_id.py` puts the same word in a CSR, and `info` compares the two --
//! so the two definitions of "dirty" have to be the same one. In particular
//! this uses plain `--porcelain`, which counts untracked files: a build with an
//! untracked file present is called dirty by both sides, and agreeing matters
//! more here than being narrow, since disagreeing would report a mismatch that
//! is not one.
//!
//! ## Staleness
//!
//! Cargo would happily keep a cached "clean" from before an edit. The rerun
//! triggers below are `src/`, `Cargo.toml` and git's own `HEAD` and `index`, so
//! a commit, a checkout, a staged change or any firmware source edit re-runs
//! this. A working-tree edit to a file OUTSIDE this crate -- gateware, docs --
//! re-runs it only once something refreshes git's index; that window is the
//! known limit of this mechanism, and the gateware's own word is what catches
//! the case that matters.

use std::env;
use std::fs;
use std::path::PathBuf;
use std::process::Command;

fn git(args: &[&str]) -> Option<String> {
    let manifest = env::var("CARGO_MANIFEST_DIR").ok()?;
    let output = Command::new("git")
        .args(args)
        .current_dir(manifest)
        .output()
        .ok()?;
    if !output.status.success() {
        return None;
    }
    Some(String::from_utf8_lossy(&output.stdout).trim().to_string())
}

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    println!("cargo::rerun-if-changed={}", manifest.join("src").display());
    println!(
        "cargo::rerun-if-changed={}",
        manifest.join("Cargo.toml").display()
    );
    println!("cargo::rerun-if-changed=build.rs");
    // Absolute, because `.git` is a FILE in a worktree and the real directory is
    // elsewhere. Asking git avoids having to know that.
    if let Some(dir) = git(&["rev-parse", "--absolute-git-dir"]) {
        let dir = PathBuf::from(dir);
        println!("cargo::rerun-if-changed={}", dir.join("HEAD").display());
        println!("cargo::rerun-if-changed={}", dir.join("index").display());
    }

    // Seven digits, because that is what `usercode()` stamps and what the
    // gateware's register carries. A build outside a git tree gets zeros, which
    // `info` prints as "no git" rather than as a hash of all zeros.
    let hash = git(&["rev-parse", "--short=7", "HEAD"]).unwrap_or_default();
    let branch = git(&["rev-parse", "--abbrev-ref", "HEAD"]).unwrap_or_else(|| "?".into());
    let dirty = git(&["status", "--porcelain"])
        .map(|text| !text.is_empty())
        .unwrap_or(false);

    let word = u32::from_str_radix(&hash, 16).unwrap_or(0) & 0x7fff_ffff
        | if dirty { 0x8000_0000 } else { 0 };

    // ISO 8601 with the builder's offset, from `date`, because a no_std target
    // has no calendar and this crate has no dependencies that would add one.
    // The offset is part of the value: "21:34" means nothing on its own, and
    // this project's boards are read in AEST while its logs are read anywhere.
    let built = Command::new("date")
        .arg("-Iseconds")
        .output()
        .ok()
        .filter(|out| out.status.success())
        .map(|out| String::from_utf8_lossy(&out.stdout).trim().to_string())
        .unwrap_or_else(|| "unknown".into());

    // Cargo hands the build script the compiler it is using, so this is the one
    // that built the image rather than whatever `rustc` is first on PATH.
    let rustc = env::var("RUSTC")
        .ok()
        .and_then(|rustc| Command::new(rustc).arg("--version").output().ok())
        .map(|out| String::from_utf8_lossy(&out.stdout).trim().to_string())
        .unwrap_or_else(|| "unknown".into());

    let target = env::var("TARGET").unwrap_or_else(|_| "unknown".into());
    let profile = env::var("PROFILE").unwrap_or_else(|_| "unknown".into());

    let out = PathBuf::from(env::var("OUT_DIR").unwrap()).join("build_info.rs");
    fs::write(
        &out,
        format!(
            "// Generated by build.rs. Included by src/info.rs.\n\
         pub const GIT_HASH: &str = {hash:?};\n\
         pub const GIT_BRANCH: &str = {branch:?};\n\
         pub const GIT_DIRTY: bool = {dirty};\n\
         /// The same 32 bits `gateware/build_helpers.py` stamps into USERCODE.\n\
         pub const GIT_WORD: u32 = {word:#010x};\n\
         pub const BUILT: &str = {built:?};\n\
         pub const RUSTC: &str = {rustc:?};\n\
         pub const TARGET: &str = {target:?};\n\
         pub const PROFILE: &str = {profile:?};\n"
        ),
    )
    .unwrap();
}
