//! Where each peripheral is. Generated by `scripts/soc_generate_pac.py`.
//!
//! Read out of `CynthionSoC.decoder.bus.memory_map` -- the SoC's own
//! description of itself -- not transcribed. Do not edit: the next run
//! overwrites this file, and a hand edit here would recreate exactly the
//! drift the generator exists to remove.
//!
//! These are `usize` rather than `svd2rust`'s `PTR` constants because
//! Rust cannot cast a pointer to an integer in a const context, and
//! `target.rs` needs const addresses.

/// ram: 65536 bytes of memory at 0x00000000
pub const RAM: usize = 0x00000000;
/// Size of the RAM window, in bytes.
pub const RAM_SIZE: usize = 0x00010000;

/// spiflash: 4194304 bytes of memory at 0x10000000
pub const SPIFLASH: usize = 0x10000000;
/// Size of the SPIFLASH window, in bytes.
pub const SPIFLASH_SIZE: usize = 0x00400000;

/// hyperram: 8388608 bytes of memory at 0x20000000
pub const HYPERRAM: usize = 0x20000000;
/// Size of the HYPERRAM window, in bytes.
pub const HYPERRAM_SIZE: usize = 0x00800000;

/// console: 8 registers at 0xf0000000
pub const CONSOLE: usize = 0xf0000000;
/// Size of the CONSOLE window, in bytes.
pub const CONSOLE_SIZE: usize = 0x00000008;
/// PLIC source number wired to CONSOLE.
pub const CONSOLE_IRQ: u32 = 1;

/// spi0: 5 registers at 0xf0000100
pub const SPI0: usize = 0xf0000100;
/// Size of the SPI0 window, in bytes.
pub const SPI0_SIZE: usize = 0x00000040;

/// flash_probe: 6 registers at 0xf0000200
pub const FLASH_PROBE: usize = 0xf0000200;
/// Size of the FLASH_PROBE window, in bytes.
pub const FLASH_PROBE_SIZE: usize = 0x00000020;

/// hyperram_probe: 14 registers at 0xf0000280
pub const HYPERRAM_PROBE: usize = 0xf0000280;
/// Size of the HYPERRAM_PROBE window, in bytes.
pub const HYPERRAM_PROBE_SIZE: usize = 0x00000040;

/// flash_ila: 4 registers at 0xf0000300
pub const FLASH_ILA: usize = 0xf0000300;
/// Size of the FLASH_ILA window, in bytes.
pub const FLASH_ILA_SIZE: usize = 0x00000020;

/// bootram: 6 registers at 0xf0000400
pub const BOOTRAM: usize = 0xf0000400;
/// Size of the BOOTRAM window, in bytes.
pub const BOOTRAM_SIZE: usize = 0x00000020;

/// apollo_uart: 8 registers at 0xf0000500
pub const APOLLO_UART: usize = 0xf0000500;
/// Size of the APOLLO_UART window, in bytes.
pub const APOLLO_UART_SIZE: usize = 0x00000008;
/// PLIC source number wired to APOLLO_UART.
pub const APOLLO_UART_IRQ: u32 = 2;

/// board/gpio: 4 registers at 0xf0000600
pub const BOARD_GPIO: usize = 0xf0000600;
/// Size of the BOARD_GPIO window, in bytes.
pub const BOARD_GPIO_SIZE: usize = 0x00000010;

/// board/i2c: 5 registers at 0xf0000610
pub const BOARD_I2C: usize = 0xf0000610;
/// Size of the BOARD_I2C window, in bytes.
pub const BOARD_I2C_SIZE: usize = 0x00000008;
/// PLIC source number wired to BOARD_I2C.
pub const BOARD_I2C_IRQ: u32 = 3;

/// board/sideband: 4 registers at 0xf0000618
pub const BOARD_SIDEBAND: usize = 0xf0000618;
/// Size of the BOARD_SIDEBAND window, in bytes.
pub const BOARD_SIDEBAND_SIZE: usize = 0x00000004;

/// board/ulpi: 4 registers at 0xf000061c
pub const BOARD_ULPI: usize = 0xf000061c;
/// Size of the BOARD_ULPI window, in bytes.
pub const BOARD_ULPI_SIZE: usize = 0x00000004;

/// board/i2c_mux: 2 registers at 0xf0000620
pub const BOARD_I2C_MUX: usize = 0xf0000620;
/// Size of the BOARD_I2C_MUX window, in bytes.
pub const BOARD_I2C_MUX_SIZE: usize = 0x00000002;
/// PLIC source number wired to BOARD_I2C_MUX_TARGET.
pub const BOARD_I2C_MUX_TARGET_IRQ: u32 = 4;
/// PLIC source number wired to BOARD_I2C_MUX_AUX.
pub const BOARD_I2C_MUX_AUX_IRQ: u32 = 5;

/// board/vbus: 2 registers at 0xf0000624
pub const BOARD_VBUS: usize = 0xf0000624;
/// Size of the BOARD_VBUS window, in bytes.
pub const BOARD_VBUS_SIZE: usize = 0x00000004;

/// board/gateware: 7 registers at 0xf0000640
pub const BOARD_GATEWARE: usize = 0xf0000640;
/// Size of the BOARD_GATEWARE window, in bytes.
pub const BOARD_GATEWARE_SIZE: usize = 0x00000020;

/// plic: 9 registers at 0xf0400000
pub const PLIC: usize = 0xf0400000;
/// Size of the PLIC window, in bytes.
pub const PLIC_SIZE: usize = 0x00400000;

/// clint: 5 registers at 0xf0800000
pub const CLINT: usize = 0xf0800000;
/// Size of the CLINT window, in bytes.
pub const CLINT_SIZE: usize = 0x00010000;

/// The `sync` clock, in Hz, from the SoC's own `SYNC_MHZ`.
///
/// `rdtime` counts one per `sync` cycle, so this is the timebase for
/// every interval in the firmware. Hand-maintained it silently stretched
/// or shrank them all whenever the gateware clock moved.
pub const SYNC_HZ: u32 = 30000000;

/// I2C prescale for 80 kHz SCL at that clock, from the gateware's own
/// `prescale_for` -- `f_SCL = f_sync / (5 * (PRER + 1))`.
pub const I2C_PRESCALE: u16 = 74;

/// Whether the SPIFLASH window is cached (VexiiRiscv PMA `main`).
///
/// From `FLASH_CACHED` in the SoC script, not from the memory map:
/// cacheability is a property of the CPU's region table, so no window
/// description carries it. Uncached routes the window to the `iobus`,
/// where every load is a full SPI command/address/dummy/data
/// transaction and the I-cache cannot fetch from it at all.
pub const SPIFLASH_CACHED: bool = true;
