//! What this machine contains. Generated by `scripts/soc_generate_pac.py`.
//!
//! Do not edit: the next run overwrites it. Both tables come from the
//! SoC's own memory map and the platform's own resource list, so neither
//! can drift from the design the way a hand-written table does.

/// One peripheral window.
pub struct Peripheral {
    pub name: &'static str,
    pub base: usize,
    pub size: usize,
    /// How many registers the memory map declares. Zero for a memory
    /// window, which holds one resource spanning the whole thing.
    pub registers: u16,
}

pub static PERIPHERALS: &[Peripheral] = &[
    Peripheral {
        name: "ram",
        base: 0x00000000,
        size: 0x00008000,
        registers: 1,
    },
    Peripheral {
        name: "spiflash",
        base: 0x10000000,
        size: 0x00400000,
        registers: 1,
    },
    Peripheral {
        name: "hyperram",
        base: 0x20000000,
        size: 0x00800000,
        registers: 1,
    },
    Peripheral {
        name: "console",
        base: 0xf0000000,
        size: 0x00000008,
        registers: 8,
    },
    Peripheral {
        name: "spi0",
        base: 0xf0000100,
        size: 0x00000040,
        registers: 5,
    },
    Peripheral {
        name: "flash_probe",
        base: 0xf0000200,
        size: 0x00000020,
        registers: 6,
    },
    Peripheral {
        name: "hyperram_probe",
        base: 0xf0000280,
        size: 0x00000040,
        registers: 14,
    },
    Peripheral {
        name: "bootram",
        base: 0xf0000400,
        size: 0x00000020,
        registers: 6,
    },
    Peripheral {
        name: "apollo_uart",
        base: 0xf0000500,
        size: 0x00000008,
        registers: 8,
    },
    Peripheral {
        name: "board_gpio",
        base: 0xf0000600,
        size: 0x00000010,
        registers: 4,
    },
    Peripheral {
        name: "board_i2c",
        base: 0xf0000610,
        size: 0x00000008,
        registers: 5,
    },
    Peripheral {
        name: "board_sideband",
        base: 0xf0000618,
        size: 0x00000004,
        registers: 4,
    },
    Peripheral {
        name: "board_ulpi",
        base: 0xf000061c,
        size: 0x00000004,
        registers: 4,
    },
    Peripheral {
        name: "board_i2c_mux",
        base: 0xf0000620,
        size: 0x00000002,
        registers: 2,
    },
    Peripheral {
        name: "board_vbus",
        base: 0xf0000624,
        size: 0x00000004,
        registers: 1,
    },
    Peripheral {
        name: "board_fabric",
        base: 0xf0000640,
        size: 0x00000008,
        registers: 2,
    },
    Peripheral {
        name: "board_clocks",
        base: 0xf0000660,
        size: 0x00000010,
        registers: 2,
    },
    Peripheral {
        name: "hyperram_bist",
        base: 0xf0000800,
        size: 0x00000200,
        registers: 64,
    },
    Peripheral {
        name: "hyperram_ck",
        base: 0xf0000a00,
        size: 0x00000010,
        registers: 4,
    },
    Peripheral {
        name: "intc",
        base: 0xf0000c00,
        size: 0x00000008,
        registers: 2,
    },
    Peripheral {
        name: "clint",
        base: 0xf0800000,
        size: 0x00010000,
        registers: 5,
    },
];

/// One pin on a physical connector.
pub struct ConnectorPin {
    pub connector: &'static str,
    /// The number printed on the connector, not an index.
    pub pin: &'static str,
    /// The FPGA ball.
    pub ball: &'static str,
    /// The platform resource that declares it, or "" when the pin is
    /// on no resource at all.
    pub resource: &'static str,
    /// Whether the SoC's `elaborate()` requested that resource. A pin
    /// with a resource nobody requested is FREE.
    pub claimed: bool,
}

pub static CONNECTOR_PINS: &[ConnectorPin] = &[
    ConnectorPin {
        connector: "mezzanine0",
        pin: "3",
        ball: "B8",
        resource: "user_mezzanine",
        claimed: false,
    },
    ConnectorPin {
        connector: "mezzanine0",
        pin: "4",
        ball: "A9",
        resource: "user_mezzanine",
        claimed: false,
    },
    ConnectorPin {
        connector: "mezzanine0",
        pin: "5",
        ball: "B10",
        resource: "user_mezzanine",
        claimed: false,
    },
    ConnectorPin {
        connector: "mezzanine0",
        pin: "6",
        ball: "A10",
        resource: "user_mezzanine",
        claimed: false,
    },
    ConnectorPin {
        connector: "mezzanine0",
        pin: "7",
        ball: "B11",
        resource: "user_mezzanine",
        claimed: false,
    },
    ConnectorPin {
        connector: "mezzanine0",
        pin: "8",
        ball: "D14",
        resource: "user_mezzanine",
        claimed: false,
    },
    ConnectorPin {
        connector: "mezzanine0",
        pin: "9",
        ball: "C14",
        resource: "user_mezzanine",
        claimed: false,
    },
    ConnectorPin {
        connector: "mezzanine0",
        pin: "10",
        ball: "F14",
        resource: "user_mezzanine",
        claimed: false,
    },
    ConnectorPin {
        connector: "mezzanine0",
        pin: "11",
        ball: "E14",
        resource: "user_mezzanine",
        claimed: false,
    },
    ConnectorPin {
        connector: "mezzanine0",
        pin: "12",
        ball: "G13",
        resource: "user_mezzanine",
        claimed: false,
    },
    ConnectorPin {
        connector: "mezzanine0",
        pin: "13",
        ball: "G12",
        resource: "user_mezzanine",
        claimed: false,
    },
    ConnectorPin {
        connector: "mezzanine0",
        pin: "18",
        ball: "C16",
        resource: "user_mezzanine",
        claimed: false,
    },
    ConnectorPin {
        connector: "mezzanine0",
        pin: "19",
        ball: "C15",
        resource: "user_mezzanine",
        claimed: false,
    },
    ConnectorPin {
        connector: "mezzanine0",
        pin: "20",
        ball: "B16",
        resource: "user_mezzanine",
        claimed: false,
    },
    ConnectorPin {
        connector: "mezzanine0",
        pin: "21",
        ball: "B15",
        resource: "user_mezzanine",
        claimed: false,
    },
    ConnectorPin {
        connector: "mezzanine0",
        pin: "22",
        ball: "A14",
        resource: "user_mezzanine",
        claimed: false,
    },
    ConnectorPin {
        connector: "mezzanine0",
        pin: "23",
        ball: "B13",
        resource: "user_mezzanine",
        claimed: false,
    },
    ConnectorPin {
        connector: "mezzanine0",
        pin: "24",
        ball: "A13",
        resource: "user_mezzanine",
        claimed: false,
    },
    ConnectorPin {
        connector: "mezzanine0",
        pin: "25",
        ball: "D13",
        resource: "user_mezzanine",
        claimed: false,
    },
    ConnectorPin {
        connector: "mezzanine0",
        pin: "26",
        ball: "A12",
        resource: "user_mezzanine",
        claimed: false,
    },
    ConnectorPin {
        connector: "mezzanine0",
        pin: "27",
        ball: "B12",
        resource: "user_mezzanine",
        claimed: false,
    },
    ConnectorPin {
        connector: "mezzanine0",
        pin: "28",
        ball: "A11",
        resource: "user_mezzanine",
        claimed: false,
    },
    ConnectorPin {
        connector: "pmod0",
        pin: "1",
        ball: "C9",
        resource: "user_pmod",
        claimed: false,
    },
    ConnectorPin {
        connector: "pmod0",
        pin: "2",
        ball: "B9",
        resource: "user_pmod",
        claimed: false,
    },
    ConnectorPin {
        connector: "pmod0",
        pin: "3",
        ball: "D11",
        resource: "user_pmod",
        claimed: false,
    },
    ConnectorPin {
        connector: "pmod0",
        pin: "4",
        ball: "C12",
        resource: "user_pmod",
        claimed: false,
    },
    ConnectorPin {
        connector: "pmod0",
        pin: "7",
        ball: "C8",
        resource: "user_pmod",
        claimed: false,
    },
    ConnectorPin {
        connector: "pmod0",
        pin: "8",
        ball: "D8",
        resource: "user_pmod",
        claimed: false,
    },
    ConnectorPin {
        connector: "pmod0",
        pin: "9",
        ball: "D9",
        resource: "user_pmod",
        claimed: false,
    },
    ConnectorPin {
        connector: "pmod0",
        pin: "10",
        ball: "C10",
        resource: "user_pmod",
        claimed: false,
    },
    ConnectorPin {
        connector: "pmod1",
        pin: "1",
        ball: "B4",
        resource: "user_pmod1",
        claimed: false,
    },
    ConnectorPin {
        connector: "pmod1",
        pin: "2",
        ball: "B5",
        resource: "user_pmod1",
        claimed: false,
    },
    ConnectorPin {
        connector: "pmod1",
        pin: "3",
        ball: "B6",
        resource: "user_pmod1",
        claimed: false,
    },
    ConnectorPin {
        connector: "pmod1",
        pin: "4",
        ball: "B7",
        resource: "user_pmod1",
        claimed: false,
    },
    ConnectorPin {
        connector: "pmod1",
        pin: "7",
        ball: "C5",
        resource: "user_pmod1",
        claimed: false,
    },
    ConnectorPin {
        connector: "pmod1",
        pin: "8",
        ball: "A5",
        resource: "user_pmod1",
        claimed: false,
    },
    ConnectorPin {
        connector: "pmod1",
        pin: "9",
        ball: "A6",
        resource: "user_pmod1",
        claimed: false,
    },
    ConnectorPin {
        connector: "pmod1",
        pin: "10",
        ball: "A7",
        resource: "user_pmod1",
        claimed: false,
    },
];
