#![doc = "Peripheral access API for CYNTHION_SOC microcontrollers (generated using svd2rust v0.37.1 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_cfg))]
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[doc(hidden)]
pub mod interrupt;
pub use self::interrupt::Interrupt;
#[doc = "console: 8 registers at 0xf0000000"]
pub type Console = crate::Periph<console::RegisterBlock, 0xf000_0000>;
impl core::fmt::Debug for Console {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Console").finish()
    }
}
#[doc = "console: 8 registers at 0xf0000000"]
pub mod console;
#[doc = "spi0: 5 registers at 0xf0000100"]
pub type Spi0 = crate::Periph<spi0::RegisterBlock, 0xf000_0100>;
impl core::fmt::Debug for Spi0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi0").finish()
    }
}
#[doc = "spi0: 5 registers at 0xf0000100"]
pub mod spi0;
#[doc = "flash_probe: 6 registers at 0xf0000200"]
pub type FlashProbe = crate::Periph<flash_probe::RegisterBlock, 0xf000_0200>;
impl core::fmt::Debug for FlashProbe {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("FlashProbe").finish()
    }
}
#[doc = "flash_probe: 6 registers at 0xf0000200"]
pub mod flash_probe;
#[doc = "hyperram_probe: 14 registers at 0xf0000280"]
pub type HyperramProbe = crate::Periph<hyperram_probe::RegisterBlock, 0xf000_0280>;
impl core::fmt::Debug for HyperramProbe {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("HyperramProbe").finish()
    }
}
#[doc = "hyperram_probe: 14 registers at 0xf0000280"]
pub mod hyperram_probe;
#[doc = "bootram: 6 registers at 0xf0000400"]
pub type Bootram = crate::Periph<bootram::RegisterBlock, 0xf000_0400>;
impl core::fmt::Debug for Bootram {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Bootram").finish()
    }
}
#[doc = "bootram: 6 registers at 0xf0000400"]
pub mod bootram;
#[doc = "apollo_uart: 8 registers at 0xf0000500"]
pub type ApolloUart = crate::Periph<apollo_uart::RegisterBlock, 0xf000_0500>;
impl core::fmt::Debug for ApolloUart {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("ApolloUart").finish()
    }
}
#[doc = "apollo_uart: 8 registers at 0xf0000500"]
pub mod apollo_uart;
#[doc = "board/gpio: 4 registers at 0xf0000600"]
pub type BoardGpio = crate::Periph<board_gpio::RegisterBlock, 0xf000_0600>;
impl core::fmt::Debug for BoardGpio {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("BoardGpio").finish()
    }
}
#[doc = "board/gpio: 4 registers at 0xf0000600"]
pub mod board_gpio;
#[doc = "board/i2c: 5 registers at 0xf0000610"]
pub type BoardI2c = crate::Periph<board_i2c::RegisterBlock, 0xf000_0610>;
impl core::fmt::Debug for BoardI2c {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("BoardI2c").finish()
    }
}
#[doc = "board/i2c: 5 registers at 0xf0000610"]
pub mod board_i2c;
#[doc = "board/sideband: 4 registers at 0xf0000618"]
pub type BoardSideband = crate::Periph<board_sideband::RegisterBlock, 0xf000_0618>;
impl core::fmt::Debug for BoardSideband {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("BoardSideband").finish()
    }
}
#[doc = "board/sideband: 4 registers at 0xf0000618"]
pub mod board_sideband;
#[doc = "board/ulpi: 4 registers at 0xf000061c"]
pub type BoardUlpi = crate::Periph<board_ulpi::RegisterBlock, 0xf000_061c>;
impl core::fmt::Debug for BoardUlpi {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("BoardUlpi").finish()
    }
}
#[doc = "board/ulpi: 4 registers at 0xf000061c"]
pub mod board_ulpi;
#[doc = "board/i2c_mux: 2 registers at 0xf0000620"]
pub type BoardI2cMux = crate::Periph<board_i2c_mux::RegisterBlock, 0xf000_0620>;
impl core::fmt::Debug for BoardI2cMux {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("BoardI2cMux").finish()
    }
}
#[doc = "board/i2c_mux: 2 registers at 0xf0000620"]
pub mod board_i2c_mux;
#[doc = "board/vbus: 1 register at 0xf0000624"]
pub type BoardVbus = crate::Periph<board_vbus::RegisterBlock, 0xf000_0624>;
impl core::fmt::Debug for BoardVbus {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("BoardVbus").finish()
    }
}
#[doc = "board/vbus: 1 register at 0xf0000624"]
pub mod board_vbus;
#[doc = "board/fabric: 2 registers at 0xf0000640"]
pub type BoardFabric = crate::Periph<board_fabric::RegisterBlock, 0xf000_0640>;
impl core::fmt::Debug for BoardFabric {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("BoardFabric").finish()
    }
}
#[doc = "board/fabric: 2 registers at 0xf0000640"]
pub mod board_fabric;
#[doc = "board/clocks: 2 registers at 0xf0000660"]
pub type BoardClocks = crate::Periph<board_clocks::RegisterBlock, 0xf000_0660>;
impl core::fmt::Debug for BoardClocks {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("BoardClocks").finish()
    }
}
#[doc = "board/clocks: 2 registers at 0xf0000660"]
pub mod board_clocks;
#[doc = "hyperram_bist: 64 registers at 0xf0000800"]
pub type HyperramBist = crate::Periph<hyperram_bist::RegisterBlock, 0xf000_0800>;
impl core::fmt::Debug for HyperramBist {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("HyperramBist").finish()
    }
}
#[doc = "hyperram_bist: 64 registers at 0xf0000800"]
pub mod hyperram_bist;
#[doc = "hyperram_ck: 4 registers at 0xf0000a00"]
pub type HyperramCk = crate::Periph<hyperram_ck::RegisterBlock, 0xf000_0a00>;
impl core::fmt::Debug for HyperramCk {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("HyperramCk").finish()
    }
}
#[doc = "hyperram_ck: 4 registers at 0xf0000a00"]
pub mod hyperram_ck;
#[doc = "intc: 2 registers at 0xf0000c00"]
pub type Intc = crate::Periph<intc::RegisterBlock, 0xf000_0c00>;
impl core::fmt::Debug for Intc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Intc").finish()
    }
}
#[doc = "intc: 2 registers at 0xf0000c00"]
pub mod intc;
#[doc = "clint: 5 registers at 0xf0800000"]
pub type Clint = crate::Periph<clint::RegisterBlock, 0xf080_0000>;
impl core::fmt::Debug for Clint {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Clint").finish()
    }
}
#[doc = "clint: 5 registers at 0xf0800000"]
pub mod clint;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "CONSOLE"]
    pub console: Console,
    #[doc = "SPI0"]
    pub spi0: Spi0,
    #[doc = "FLASH_PROBE"]
    pub flash_probe: FlashProbe,
    #[doc = "HYPERRAM_PROBE"]
    pub hyperram_probe: HyperramProbe,
    #[doc = "BOOTRAM"]
    pub bootram: Bootram,
    #[doc = "APOLLO_UART"]
    pub apollo_uart: ApolloUart,
    #[doc = "BOARD_GPIO"]
    pub board_gpio: BoardGpio,
    #[doc = "BOARD_I2C"]
    pub board_i2c: BoardI2c,
    #[doc = "BOARD_SIDEBAND"]
    pub board_sideband: BoardSideband,
    #[doc = "BOARD_ULPI"]
    pub board_ulpi: BoardUlpi,
    #[doc = "BOARD_I2C_MUX"]
    pub board_i2c_mux: BoardI2cMux,
    #[doc = "BOARD_VBUS"]
    pub board_vbus: BoardVbus,
    #[doc = "BOARD_FABRIC"]
    pub board_fabric: BoardFabric,
    #[doc = "BOARD_CLOCKS"]
    pub board_clocks: BoardClocks,
    #[doc = "HYPERRAM_BIST"]
    pub hyperram_bist: HyperramBist,
    #[doc = "HYPERRAM_CK"]
    pub hyperram_ck: HyperramCk,
    #[doc = "INTC"]
    pub intc: Intc,
    #[doc = "CLINT"]
    pub clint: Clint,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            console: Console::steal(),
            spi0: Spi0::steal(),
            flash_probe: FlashProbe::steal(),
            hyperram_probe: HyperramProbe::steal(),
            bootram: Bootram::steal(),
            apollo_uart: ApolloUart::steal(),
            board_gpio: BoardGpio::steal(),
            board_i2c: BoardI2c::steal(),
            board_sideband: BoardSideband::steal(),
            board_ulpi: BoardUlpi::steal(),
            board_i2c_mux: BoardI2cMux::steal(),
            board_vbus: BoardVbus::steal(),
            board_fabric: BoardFabric::steal(),
            board_clocks: BoardClocks::steal(),
            hyperram_bist: HyperramBist::steal(),
            hyperram_ck: HyperramCk::steal(),
            intc: Intc::steal(),
            clint: Clint::steal(),
        }
    }
}
pub mod base;
pub mod hardware;
