// The constants that follow the build variant. Generated by
// `scripts/soc_generate_pac.py`; `base.rs` includes the copy `build.rs`
// selects. Do not edit.

/// The `sync` clock, in Hz, from the SoC's own `SYNC_MHZ`.
///
/// `rdtime` counts one per `sync` cycle, so this is the timebase for
/// every interval in the firmware. Hand-maintained it silently stretched
/// or shrank them all whenever the gateware clock moved.
pub const SYNC_HZ: u32 = 60000000;

/// I2C prescale for 1000 kHz SCL at that clock, from the
/// gateware's own `prescale_for` -- `f_SCL = f_sync / (5 * (PRER + 1))`.
///
/// Getting it wrong gives a bus that violates its own setup times and
/// answers most of the time.
pub const I2C_PRESCALE: u16 = 11;
