#!/usr/bin/env python3
"""Record ECP5 resource/timing usage into a CSV ledger.

Reads the latest timing summary and relevant logs from out/sim and appends one
row to metrics/ecp5_usage_history.csv so we can track growth as features are
added to the RV64 core.
"""

from __future__ import annotations

import argparse
import csv
import datetime as dt
import pathlib
import re
import subprocess
import sys
from typing import Optional

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
SIM_DIR = REPO_ROOT / "riscv-64" / "out" / "sim"
METRICS_DIR = REPO_ROOT / "riscv-64" / "metrics"
CSV_PATH = METRICS_DIR / "ecp5_usage_history.csv"


CSV_FIELDS = [
    "timestamp",
    "git_commit",
    "tag",
    "device",
    "package",
    "speed",
    "luts_used",
    "luts_total",
    "luts_pct",
    "ffs_used",
    "ffs_total",
    "ffs_pct",
    "bram_used",
    "bram_total",
    "bram_pct",
    "fmax_mhz",
    "target_mhz",
    "timing_pass",
    "source_log",
    "notes",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--timing-summary",
        type=pathlib.Path,
        default=SIM_DIR / "vexii_ecp5_timing_summary.txt",
        help="Path to timing summary generated by script 42.",
    )
    parser.add_argument(
        "--nextpnr-log",
        type=pathlib.Path,
        default=SIM_DIR / "vexii_ecp5_nextpnr.log",
        help="Path to nextpnr log containing utilization details.",
    )
    parser.add_argument(
        "--yosys-log",
        type=pathlib.Path,
        default=SIM_DIR / "vexii_ecp5_yosys.log",
        help="Path to yosys log (optional fallback).",
    )
    parser.add_argument(
        "--tag",
        default="baseline",
        help="Build ID for this datapoint; include major features in the tag itself.",
    )
    parser.add_argument(
        "--target-mhz",
        type=float,
        default=25.0,
        help="Timing target used for PASS/FAIL evaluation.",
    )
    parser.add_argument(
        "--notes",
        default="",
        help="Optional freeform notes.",
    )
    parser.add_argument(
        "--csv",
        type=pathlib.Path,
        default=CSV_PATH,
        help="Output CSV path.",
    )
    return parser.parse_args()


def read_text(path: pathlib.Path) -> str:
    if not path.exists():
        raise FileNotFoundError(f"Missing required file: {path}")
    return path.read_text(encoding="utf-8", errors="replace")


def parse_summary(summary_text: str) -> tuple[str, str, str, Optional[float]]:
    # Example: max_frequencies_mhz=76.19, 95.07
    fmax_matches = re.findall(r"([0-9]+(?:\.[0-9]+)?)", _line_after_key(summary_text, "max_frequencies_mhz="))
    fmax = max((float(v) for v in fmax_matches), default=None)

    # We currently hardcode from known flow unless device appears in logs.
    device = "LFE5U-12F"
    package = "BG256"
    speed = "8"
    return device, package, speed, fmax


def _line_after_key(text: str, key: str) -> str:
    for line in text.splitlines():
        if key in line:
            return line
    return ""


def parse_util_from_nextpnr(nextpnr_text: str) -> tuple[Optional[int], Optional[int], Optional[int], Optional[int], Optional[int], Optional[int]]:
    """Return (luts_used, luts_total, ffs_used, ffs_total, bram_used, bram_total)."""

    def parse_pair(pattern: str) -> tuple[Optional[int], Optional[int]]:
        m = re.search(pattern, nextpnr_text, flags=re.IGNORECASE)
        if not m:
            return None, None
        return int(m.group(1)), int(m.group(2))

    # Common nextpnr line variants include:
    #   Info: LUT4            5336/8364     63%
    #   Info: Total LUT4s:    2351/24288     9%
    #   Info: TRELLIS_FF      3000/8364     35%
    #   Info: Total DFFs:      895/24288     3%
    #   Info: DP16KD             0/56        0%
    luts_used, luts_total = parse_pair(r"\bLUT4\b\s+([0-9]+)/([0-9]+)")
    if luts_used is None:
        luts_used, luts_total = parse_pair(r"\bTotal\s+LUT4s\s*:\s*([0-9]+)/([0-9]+)")

    ffs_used, ffs_total = parse_pair(r"\bTRELLIS_FF\b\s+([0-9]+)/([0-9]+)")
    if ffs_used is None:
        ffs_used, ffs_total = parse_pair(r"\bTotal\s+DFFs\s*:\s*([0-9]+)/([0-9]+)")

    bram_used, bram_total = parse_pair(r"\bDP16KD\b\s*:\s*([0-9]+)\s*/\s*([0-9]+)")
    return luts_used, luts_total, ffs_used, ffs_total, bram_used, bram_total


def pct(used: Optional[int], total: Optional[int]) -> Optional[float]:
    if used is None or total in (None, 0):
        return None
    return (used / total) * 100.0


def get_git_commit() -> str:
    try:
        result = subprocess.run(
            ["git", "-C", str(REPO_ROOT), "rev-parse", "--short", "HEAD"],
            check=True,
            capture_output=True,
            text=True,
        )
        return result.stdout.strip()
    except Exception:
        return "unknown"


def append_row(csv_path: pathlib.Path, row: dict[str, object]) -> None:
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    file_exists = csv_path.exists()
    with csv_path.open("a", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=CSV_FIELDS)
        if not file_exists:
            writer.writeheader()
        writer.writerow(row)


def main() -> int:
    args = parse_args()

    summary_text = read_text(args.timing_summary)
    nextpnr_text = read_text(args.nextpnr_log)

    device, package, speed, fmax = parse_summary(summary_text)
    luts_used, luts_total, ffs_used, ffs_total, bram_used, bram_total = parse_util_from_nextpnr(nextpnr_text)

    if luts_used is None or luts_total is None:
        print("ERROR: Could not parse LUT usage from nextpnr log", file=sys.stderr)
        return 2

    timestamp = dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")
    target = float(args.target_mhz)
    timing_pass = (fmax is not None) and (fmax >= target)

    row = {
        "timestamp": timestamp,
        "git_commit": get_git_commit(),
        "tag": args.tag,
        "device": device,
        "package": package,
        "speed": speed,
        "luts_used": luts_used,
        "luts_total": luts_total,
        "luts_pct": f"{pct(luts_used, luts_total):.2f}" if pct(luts_used, luts_total) is not None else "",
        "ffs_used": ffs_used if ffs_used is not None else "",
        "ffs_total": ffs_total if ffs_total is not None else "",
        "ffs_pct": f"{pct(ffs_used, ffs_total):.2f}" if pct(ffs_used, ffs_total) is not None else "",
        "bram_used": bram_used if bram_used is not None else "",
        "bram_total": bram_total if bram_total is not None else "",
        "bram_pct": f"{pct(bram_used, bram_total):.2f}" if pct(bram_used, bram_total) is not None else "",
        "fmax_mhz": f"{fmax:.2f}" if fmax is not None else "",
        "target_mhz": f"{target:.2f}",
        "timing_pass": "yes" if timing_pass else "no",
        "source_log": str(args.nextpnr_log.relative_to(REPO_ROOT)),
        "notes": args.notes,
    }

    append_row(args.csv, row)

    print("Recorded ECP5 metrics row:")
    for k in CSV_FIELDS:
        print(f"  {k}: {row.get(k, '')}")
    print(f"CSV: {args.csv}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
