#!/usr/bin/env python3
#
# An I2C master with the OpenCores register map, in front of the board's I2C pins.
# SPDX-License-Identifier: BSD-3-Clause

"""
A single-master I2C controller, deliberately unremarkable, for the same reason
`peripherals/uart16550.py` is a 16550: the interesting part of a peripheral is the part that
is already written down somewhere else.

The register map is the OpenCores "I2C-Master Core" (Richard Herveille,
opencores.org, rev 0.9). That specification is public, it has a Linux driver
(`drivers/i2c/busses/i2c-ocores.c`), and -- the reason it was chosen over
inventing one -- **it has no read with a side effect anywhere in it**. Status is
read from SR, which is pure; the interrupt flag is cleared by *writing* IACK,
not by reading anything. The one place a register map usually goes wrong is
already right here.

`amaranth-soc` has no I2C peripheral (it has `gpio`, `event`, `memory` and the
bus fabric, and nothing else), so this is written rather than imported.

## The register map

    +0  PRERlo  RW  clock prescale, low byte
    +1  PRERhi  RW  clock prescale, high byte
    +2  CTR     RW  bit 7 EN (core enable), bit 6 IEN (interrupt enable)
    +3  TXR (W) / RXR (R)   byte to send / byte received
    +4  CR  (W) / SR  (R)   command / status

    CR:  bit 7 STA   generate a START before the transfer
         bit 6 STO   generate a STOP after it
         bit 5 RD    read a byte
         bit 4 WR    write the byte in TXR
         bit 3 ACK   what to send after a read: 0 = ACK, 1 = NACK
         bit 0 IACK  clear the interrupt flag

    SR:  bit 7 RxACK the acknowledge received from the slave: 0 = ACK, 1 = NACK
         bit 6 BUSY  a START has been sent and no STOP yet
         bit 5 AL    arbitration lost -- see below
         bit 1 TIP   a transfer is in progress
         bit 0 IF    a transfer finished; write CR.IACK to clear

## Register discipline

The rule this project enforces is that **a read must never change state, and a
status register must never share a 32-bit word with a side-effecting register**
(the full argument is in `peripherals/uart16550.py`). Checked against this map:

  * Every readable address here -- PRERlo, PRERhi, CTR, RXR, SR -- is a plain
    latch or a wire from a flag. Reading any of them twice gives the same
    answer. There is no clear-on-read bit and no FIFO to pop, so the hazard
    class that motivated the rule (a widened, prefetched, speculated or replayed
    read consuming something) cannot arise at all. RXR in particular is a
    *register*, not a FIFO head: reading it does not advance anything.
  * The only side-effecting address is CR at +4, and it is side-effecting on
    **write**. Writes are never speculative, never prefetched and never
    replayed, so sharing address +4 with SR costs nothing -- it is the same
    arrangement as the 16550's IIR/FCR, expressed with the same `SplitRW`
    field action.
  * CR is nonetheless in the *second* 32-bit word (bytes 0..3 are word 0, byte 4
    is word 1), so even a bus master that only ever wrote whole words could not
    strobe a command as a side effect of setting the prescale.

## What is not implemented, and why

**Clock stretching.** The board's `power_monitor.scl` is `Pins("D7", dir="o")` --
an output, with no `oe` and therefore no way to release the line or read it back.
SCL is driven push-pull. A slave that stretched the clock would be shorting
against this driver, so this controller can only be used on a bus where nothing
stretches; the PAC1954 that is on this one does not (DS20006539B). If a part
that stretches is ever added, the platform resource has to change first, and
this paragraph is the thing that says so.

**Multi-master arbitration.** There is one master. `AL` is still implemented,
because the check that would detect a lost arbitration -- release SDA, read it
back, find it low -- is the same check that detects the failure that *does*
happen on a single-master bus: a slave that has wedged mid-transfer and is
holding SDA down. Without it, a scan of a wedged bus reads 0x00 from every
address and looks like a bus full of devices. With it, `AL` is set and the
transfer is abandoned with the pins released.

**A byte-level or transaction-level sequencer.** Commands are one bus operation
each and the ordering is the firmware's business, which is what the OpenCores
map specifies and what its Linux driver expects.

## Bit timing

SCL for a data bit is generated by dividing the `sync` clock:

    f_SCL = f_sync / (5 * (PRER + 1))

which is the OpenCores formula, unchanged. Five slots per bit period:

    slot 0    SCL low, SDA changes here and only here
    slot 1    SCL low
    slot 2    SCL high  -- the slave samples somewhere in here
    slot 3    SCL high  -- we sample at the end of this slot
    slot 4    SCL low

so t_LOW is 3 slots and t_HIGH is 2.

**START and STOP are six slots, not five.** Every interval I2C specifies has to
be at least two slots to clear standard mode at a sensible prescale, and a
condition needs a setup interval and a hold interval either side of an SDA edge
that happens while SCL is high -- which does not fit in five. Making the two
condition states one slot longer costs a fraction of a microsecond once per
transfer and keeps the *data* rate exactly on the published formula, which is
the number a driver computes a prescale from.

## Which mode's minima, and it is not standard mode

**Every device on this bus is Fast-mode Plus.** Scanned rather than assumed:

    bus 0  target_type_c   0x22  FUSB302B    fSCL 0-1000 kHz
    bus 1  aux_type_c      0x22  FUSB302B    fSCL 0-1000 kHz
    bus 2  power_monitor   0x10  PAC1954-1   fSMB 0.010-1 MHz

Nothing standard-mode is on it, and nothing ever has been, so the budget is
Fast-mode Plus. Budgeting against standard mode's 4.7 us intervals lands on
80 kHz -- t_SU;STA falls 0.7 us inside a *standard mode* minimum at 100 kHz --
and runs the bus twelve times slower than every device on it. See #269.

At 60 MHz with PRER = 11 the slot is 200 ns and the data rate is exactly 1 MHz:

    t_LOW      600 ns   Fm+ min 500 ns
    t_HIGH     400 ns   Fm+ min 260 ns
    t_SU;STA   400 ns   Fm+ min 260 ns
    t_HD;STA   400 ns   Fm+ min 260 ns
    t_SU;STO   400 ns   Fm+ min 260 ns
    t_BUF     1200 ns   Fm+ min 500 ns
    t_SU;DAT   200 ns   Fm+ min  50 ns

The tightest is t_LOW at 20% margin; the rest are above 50%.

## What actually limits the rate, and it is the board rather than this file

**SDA's rise time.** The pull-ups are 2.2k -- R83/R84 on the monitor, R97 on
target, R33 on aux, from `production/bom.csv` -- and `t_r ~= 0.8473 * R * C`
over the spec's 0.3-0.7 Vdd window:

     20 pF ->  37 ns        Fm+ allows 120 ns
     50 pF ->  93 ns        Fm  allows 300 ns
     65 pF -> 121 ns        the Fm+ edge
    100 pF -> 186 ns        Fm+ exceeded, Fm fine

Each device sits on its own mux segment, so the capacitance is one short trace
and one load rather than a bus with three. 2.2k is a Fast-mode-Plus-grade
pull-up and the sink current it implies -- 1.5 mA at 3.3 V -- is far inside every
device's capability.

**3.4 MHz is not available and not close.** The FUSB302B enumerates its modes as
"Standard, Fast, or Fast Mode Plus" and stops at 1 MHz; Hs-mode is a different
protocol needing an unacknowledged master code, a current-source pull-up on SCL,
and t_r under 40 ns, which no resistor delivers. That is why the spec mandates a
current source there.

## If this ever misbehaves

A bus marginal on rise time **answers most of the time**, which is the failure
this file warns about in another form. `i2c power`, `i2c target` and `i2c aux`
each read identity registers from a different part on a different segment, so
three independent confirmations. Falling back is one constant: `I2C_SCL_HZ`.
"""

from amaranth               import Module, Mux, Cat, C, Signal, ResetInserter
from amaranth.lib           import wiring
from amaranth.lib.cdc       import FFSynchronizer
from amaranth.lib.wiring    import In, Out

from amaranth_soc           import csr

from peripherals.uart16550              import SplitRW


__all__ = ["I2CMaster", "prescale_for", "SLOTS_BIT"]


# Slots per SCL period for a data bit. Fixed by the bit engine below and by the
# f_SCL formula in the docstring; the two must not drift apart.
SLOTS_BIT = 5

# START and STOP get one slot more. See the docstring.
SLOTS_COND = 6

# Command register bits, per the OpenCores specification.
CR_STA  = 7
CR_STO  = 6
CR_RD   = 5
CR_WR   = 4
CR_ACK  = 3
CR_IACK = 0


def prescale_for(clock_hz, scl_hz):
    """The PRER value that gives at most `scl_hz`, given `sync` at `clock_hz`.

    Rounds the divider UP, so the result is never faster than asked for. A
    prescale that overshoots is a bus that violates its own timing, and the
    failure that produces is a slave which answers most of the time.
    """
    divider = -(-int(clock_hz) // (SLOTS_BIT * int(scl_hz)))   # ceiling division
    return max(0, divider - 1)


class I2CMaster(wiring.Component):
    """The OpenCores I2C master register map, driving one bus.

    Attributes
    ----------
    bus : csr.Interface(addr_width=3, data_width=8)
        The five registers. Add through a `WishboneCSRBridge`, or behind a
        `csr.Decoder` alongside other peripherals.
    scl_o : Signal(), out
        The clock pin. Driven push-pull -- see the docstring.
    sda_o : Signal(), out
        The data pin's output value. Always 0: this is an open-drain bus, so a
        one is sent by releasing the line, not by driving it.
    sda_oe : Signal(), out
        The data pin's output enable. High only to send a zero.
    sda_i : Signal(), in
        The data pin, straight from the pad. Synchronised here.
    irq : Signal(), out
        Level, asserted while `IF and CTR.IEN`. Attach to a `vexii_plic.Plic`
        source, or leave it and poll SR.TIP -- IEN resets to zero, so this line
        is low until a driver asks for it.
    idle : Signal(), out
        High when no transfer is in progress and no START is outstanding -- the
        two status bits SR.BUSY and SR.TIP, both clear. Brought out for
        `i2c_mux.I2CBusMux`, which must not move the bus select underneath a
        transfer: switching pin-sets between a START and its STOP would leave one
        bus half-driven and put an edge on another that every device on it reads
        as a START. Nothing else needs it, and a driver can read the same two
        bits from SR.
    """

    def __init__(self):
        # +0, +1. The prescale, in two bytes because a CSR register here is
        # eight bits wide and a useful divider is not.
        self._prer_lo = csr.Register({"data": csr.Field(csr.action.RW, 8)},
                                     access="rw")
        self._prer_hi = csr.Register({"data": csr.Field(csr.action.RW, 8)},
                                     access="rw")
        # +2. CTR. Only EN and IEN are defined; the rest read back as written so
        # a driver that saves and restores the register is not surprised.
        self._ctr = csr.Register({"data": csr.Field(csr.action.RW, 8)},
                                 access="rw")
        # +3. TXR on write, RXR on read. Genuinely two registers, as on the
        # original core -- writing the byte to send does not disturb the byte
        # last received, which matters because a driver reads RXR after the
        # transfer that filled it and may have written TXR since.
        self._txr_rxr = csr.Register({"data": csr.Field(SplitRW, 8)},
                                     access="rw")
        # +4. CR on write, SR on read. The only side-effecting address, and it
        # is side-effecting on write only.
        self._cr_sr = csr.Register({"data": csr.Field(SplitRW, 8)},
                                   access="rw")

        builder = csr.Builder(addr_width=3, data_width=8)
        builder.add("prer_lo", self._prer_lo)
        builder.add("prer_hi", self._prer_hi)
        builder.add("ctr",     self._ctr)
        builder.add("txr_rxr", self._txr_rxr)
        builder.add("cr_sr",   self._cr_sr)
        self._bridge = csr.Bridge(builder.as_memory_map())

        super().__init__({
            "bus":    In(csr.Signature(addr_width=3, data_width=8)),
            "scl_o":  Out(1, init=1),
            "sda_o":  Out(1),
            "sda_oe": Out(1),
            "sda_i":  In(1),
            "irq":    Out(1),
            "idle":   Out(1),
        })
        self.bus.memory_map = self._bridge.bus.memory_map

    def elaborate(self, platform):
        m = Module()
        m.submodules.bridge = self._bridge
        wiring.connect(m, wiring.flipped(self.bus), self._bridge.bus)

        ctr    = self._ctr.f.data.data
        enable = ctr[7]
        ien    = ctr[6]

        prer = Cat(self._prer_lo.f.data.data, self._prer_hi.f.data.data)

        cmd = self._cr_sr.f.data
        txr = self._txr_rxr.f.data

        # ---- the pin ---------------------------------------------------------
        #
        # SDA comes from another device's open-drain driver and its own clock, so
        # it is asynchronous to `sync`. Sampling it raw would put a metastable
        # value into the shift register and into the acknowledge bit, which reads
        # as a device that is there most of the time. `init=1` because an idle
        # I2C bus is high.
        sda_sync = Signal(init=1)
        m.submodules.sda_cdc = FFSynchronizer(self.sda_i, sda_sync, init=1)

        # ---- the slot timer --------------------------------------------------
        #
        # One tick per (PRER + 1) sync cycles. Everything in the bit engine
        # advances on `tick` and never on the raw clock, so the bit timing is a
        # property of PRER alone.
        divider = Signal(16)
        tick    = Signal()
        m.d.comb += tick.eq(divider == 0)
        with m.If(tick):
            m.d.sync += divider.eq(prer)
        with m.Else():
            m.d.sync += divider.eq(divider - 1)

        # ---- the byte to send ------------------------------------------------
        #
        # Latched here rather than read out of the CSR write port at command
        # time: TXR is written by an earlier bus cycle than CR, so `txr.w_data`
        # is long gone by the time a command arrives.
        txr_reg = Signal(8)
        with m.If(txr.w_stb):
            m.d.sync += txr_reg.eq(txr.w_data)

        # ---- state the engine owns ------------------------------------------
        #
        # `sda_low` and `scl_high` are both COMBINATIONAL decodes of the state
        # and slot, and both are registered once on the way to the pins below.
        # Registering one and not the other put the two pins a cycle apart,
        # which shortened t_HD;STA and lengthened t_SU;STO by a cycle each --
        # invisible at 80 kHz and exactly the sort of thing that stops being
        # invisible when someone raises the bus rate.
        sda_low  = Signal()
        scl_high = Signal(init=1)
        rx_ack   = Signal(init=1)      # 1 == NACK, which is what an empty bus gives
        busy     = Signal()
        arb_lost = Signal()
        tip      = Signal()
        rxr      = Signal(8)
        done     = Signal()

        # ---- the interrupt flag ---------------------------------------------
        #
        # Outside the engine, so that IACK still works on a disabled core and a
        # driver cannot be left with an interrupt it has no way to clear. Set
        # beats clear: a transfer that finishes on the same cycle as an IACK for
        # the previous one has its completion recorded rather than swallowed.
        irq_flag = Signal()
        with m.If(done):
            m.d.sync += irq_flag.eq(1)
        with m.Elif(cmd.w_stb & cmd.w_data[CR_IACK]):
            m.d.sync += irq_flag.eq(0)

        m.d.comb += [
            self._cr_sr.f.data.r_data.eq(
                Cat(irq_flag, tip, C(0, 3), arb_lost, busy, rx_ack)),
            txr.r_data.eq(rxr),
            self.irq.eq(irq_flag & ien),

            # The same two bits SR reports, as a wire. No extra state: a second
            # idea of "busy" could disagree with the one software reads.
            self.idle.eq(~busy & ~tip),

            # A one is sent by releasing the line. `sda_o` is therefore hardwired
            # to zero and only `sda_oe` ever changes: an open-drain driver that
            # could drive a one would fight every other device on the bus, and on
            # this board's `PULLMODE="NONE"` pins there is nothing but the
            # external pull-ups to win that fight.
            self.sda_o.eq(0),
        ]

        # THE PINS ARE REGISTERED, and both by the same one cycle.
        #
        # Two reasons. The alignment above is the first. The second is that
        # these go to a bus where a glitch is not noise but a message: a
        # transient on SDA while SCL is high is a START or a STOP to every
        # device listening, and a combinational decode of a state machine has
        # no guarantee of being glitch-free.
        scl_pin = Signal(init=1)
        sda_oe_pin = Signal()
        m.d.sync += [
            scl_pin.eq(scl_high | ~enable),
            sda_oe_pin.eq(sda_low & enable),
        ]
        m.d.comb += [
            self.scl_o.eq(scl_pin),
            self.sda_oe.eq(sda_oe_pin),
        ]

        # ---- the bit engine --------------------------------------------------
        #
        # In its own Module so that clearing CTR.EN can hold it in reset. Without
        # that, disabling the core mid-transfer would freeze the FSM wherever it
        # stood -- and on a push-pull SCL driver that means a bus clamped low by
        # the master, with no way back short of reconfiguring the FPGA. The CSR
        # registers, the TXR latch and the interrupt flag stay outside, so they
        # keep working while the engine is held.
        #
        # Every state is a fixed number of slots long, and what the two pins do
        # in each slot is spelled out rather than derived. The table is longer
        # than the clever version and it is the only form in which the timing
        # numbers in the docstring can be checked by reading.
        engine = Module()

        sta = Signal()
        sto = Signal()
        rd  = Signal()
        wr  = Signal()
        ack = Signal()
        shreg = Signal(8)
        bitno = Signal(range(8))
        slot  = Signal(range(SLOTS_COND))

        with engine.FSM():
            with engine.State("IDLE"):
                # SCL stays LOW between the commands of a multi-part transfer.
                # Raising it here with SDA released would be a STOP condition,
                # ending the transfer the firmware was in the middle of --
                # which is a bus that works for single-byte writes and fails
                # for every register read.
                # SDA is released here. Between the commands of a multi-part
                # transfer SCL is low, and SDA may move freely while it is --
                # the next command drives the line again at its own slot 0.
                engine.d.comb += scl_high.eq(~busy)

                with engine.If(cmd.w_stb):
                    engine.d.sync += [
                        sta.eq(cmd.w_data[CR_STA]),
                        sto.eq(cmd.w_data[CR_STO]),
                        rd .eq(cmd.w_data[CR_RD]),
                        wr .eq(cmd.w_data[CR_WR]),
                        ack.eq(cmd.w_data[CR_ACK]),
                        shreg.eq(txr_reg),
                        bitno.eq(7),
                        slot.eq(0),
                    ]
                    # A command with none of STA, STO, RD or WR set is an IACK
                    # and nothing else, and must not start a transfer.
                    with engine.If(cmd.w_data[CR_STA] | cmd.w_data[CR_STO] |
                                   cmd.w_data[CR_RD]  | cmd.w_data[CR_WR]):
                        engine.d.sync += [tip.eq(1), arb_lost.eq(0)]
                        with engine.If(cmd.w_data[CR_STA]):
                            engine.next = "START"
                        with engine.Elif(cmd.w_data[CR_WR]):
                            engine.next = "WRITE"
                        with engine.Elif(cmd.w_data[CR_RD]):
                            engine.next = "READ"
                        with engine.Else():
                            engine.next = "STOP"

            # START: SDA falls while SCL is high. Six slots.
            #
            #   slot 0  SCL as-is, SDA released  -- SDA is released with SCL
            #                                      still where IDLE left it, so
            #                                      a repeated START does not
            #                                      put an edge on a high clock
            #   slot 1  SCL high,  SDA released
            #   slot 2  SCL high,  SDA released  -- t_SU;STA is slots 1..2
            #   slot 3  SCL high,  SDA LOW       <-- the START condition
            #   slot 4  SCL high,  SDA low       -- t_HD;STA is slots 3..4
            #   slot 5  SCL low,   SDA low
            with engine.State("START"):
                engine.d.comb += [
                    scl_high.eq(Mux(slot == 0, ~busy,
                                    (slot >= 1) & (slot <= 4))),
                    sda_low.eq(slot >= 3),
                ]
                with engine.If(tick):
                    engine.d.sync += slot.eq(slot + 1)
                    with engine.If(slot == SLOTS_COND - 1):
                        engine.d.sync += [slot.eq(0), busy.eq(1)]
                        with engine.If(wr):
                            engine.next = "WRITE"
                        with engine.Elif(rd):
                            engine.next = "READ"
                        with engine.Elif(sto):
                            engine.next = "STOP"
                        with engine.Else():
                            engine.next = "DONE"

            # WRITE: eight bits, MSB first.
            with engine.State("WRITE"):
                engine.d.comb += [
                    scl_high.eq((slot == 2) | (slot == 3)),
                    # The bit is a wire from the shift register, which advances
                    # on the slot 4 -> slot 0 boundary. So SDA changes exactly
                    # where the table above says it may, and nowhere else.
                    sda_low.eq(~shreg[7]),
                ]
                with engine.If(tick):
                    engine.d.sync += slot.eq(slot + 1)
                    with engine.If(slot == 3):
                        # ARBITRATION. We released the line for a one and read
                        # back a zero, so something else is holding it down. On
                        # this single-master bus that is a wedged slave rather
                        # than a competitor, and either way continuing would
                        # produce data that is not ours.
                        with engine.If(~sda_low & ~sda_sync):
                            engine.d.sync += arb_lost.eq(1)
                            engine.next = "ABORT"
                    with engine.If(slot == SLOTS_BIT - 1):
                        engine.d.sync += [slot.eq(0), shreg.eq(shreg << 1)]
                        with engine.If(bitno == 0):
                            engine.next = "WACK"
                        with engine.Else():
                            engine.d.sync += bitno.eq(bitno - 1)

            # WACK: release SDA and read the slave's acknowledge.
            with engine.State("WACK"):
                engine.d.comb += scl_high.eq((slot == 2) | (slot == 3))
                with engine.If(tick):
                    engine.d.sync += slot.eq(slot + 1)
                    with engine.If(slot == 3):
                        engine.d.sync += rx_ack.eq(sda_sync)
                    with engine.If(slot == SLOTS_BIT - 1):
                        engine.d.sync += slot.eq(0)
                        with engine.If(sto):
                            engine.next = "STOP"
                        with engine.Else():
                            engine.next = "DONE"

            # READ: eight bits in, SDA released throughout.
            with engine.State("READ"):
                engine.d.comb += scl_high.eq((slot == 2) | (slot == 3))
                with engine.If(tick):
                    engine.d.sync += slot.eq(slot + 1)
                    with engine.If(slot == 3):
                        engine.d.sync += shreg.eq(Cat(sda_sync, shreg[:7]))
                    with engine.If(slot == SLOTS_BIT - 1):
                        engine.d.sync += slot.eq(0)
                        with engine.If(bitno == 0):
                            engine.next = "RACK"
                        with engine.Else():
                            engine.d.sync += bitno.eq(bitno - 1)

            # RACK: send the acknowledge the command asked for. CR.ACK is 0 for
            # ACK and 1 for NACK, which is the sense the OpenCores map defines
            # and the opposite of what the name suggests -- a NACK is how a
            # master says "that was the last byte", so the bit really means
            # "finish after this one".
            with engine.State("RACK"):
                engine.d.comb += [
                    scl_high.eq((slot == 2) | (slot == 3)),
                    sda_low.eq(~ack),
                ]
                with engine.If(slot == 0):
                    engine.d.sync += rxr.eq(shreg)
                with engine.If(tick):
                    engine.d.sync += slot.eq(slot + 1)
                    with engine.If(slot == SLOTS_BIT - 1):
                        engine.d.sync += slot.eq(0)
                        with engine.If(sto):
                            engine.next = "STOP"
                        with engine.Else():
                            engine.next = "DONE"

            # STOP: SDA rises while SCL is high. Six slots.
            #
            #   slot 0  SCL low,  SDA LOW      -- put SDA down first, whatever
            #   slot 1  SCL low,  SDA low         the last data bit left it at
            #   slot 2  SCL high, SDA low
            #   slot 3  SCL high, SDA low      -- t_SU;STO is slots 2..3
            #   slot 4  SCL high, SDA released <-- the STOP condition
            #   slot 5  SCL high, SDA released
            with engine.State("STOP"):
                engine.d.comb += [
                    scl_high.eq(slot >= 2),
                    sda_low.eq(slot < 4),
                ]
                with engine.If(tick):
                    engine.d.sync += slot.eq(slot + 1)
                    with engine.If(slot == SLOTS_COND - 1):
                        engine.d.sync += [slot.eq(0), busy.eq(0)]
                        engine.next = "BUS_FREE"

            # t_BUF: the bus must stay idle for a bit period after a STOP before
            # the next START. Enforced here rather than left to the firmware,
            # because firmware that got it wrong would produce a START the slave
            # ignores, and the symptom is a device that answers sometimes.
            with engine.State("BUS_FREE"):
                engine.d.comb += scl_high.eq(1)
                with engine.If(tick):
                    engine.d.sync += slot.eq(slot + 1)
                    with engine.If(slot == SLOTS_BIT - 1):
                        engine.d.sync += slot.eq(0)
                        engine.next = "DONE"

            # ABORT: arbitration lost. Release both lines and stop; the bus is
            # not ours to put a STOP on.
            with engine.State("ABORT"):
                engine.d.comb += scl_high.eq(1)
                engine.d.sync += busy.eq(0)
                engine.next = "DONE"

            with engine.State("DONE"):
                engine.d.comb += [scl_high.eq(~busy), done.eq(1)]
                engine.d.sync += tip.eq(0)
                engine.next = "IDLE"

        m.submodules.engine = ResetInserter(~enable)(engine)

        return m
