#!/usr/bin/env python3
#
# Generate and install the udev rules for this workspace's test bitstreams.
# SPDX-License-Identifier: BSD-3-Clause

"""
Generates `55-cynthion-test.rules` from `ecp5-test/usb_ids.py` and installs it.

The rules are generated rather than hand-maintained so they cannot drift from the
allocation. Adding a bitstream means adding one line to `usb_ids.py` and re-running this;
editing the rules file directly gets overwritten.

## What the rules do, and what they deliberately do not

**They grant `uaccess` and nothing else.** No `SYMLINK`. A symlink is a second name for a
device, and a second name is another thing that can be stale or point elsewhere. Code
resolves devices by VID:PID from sysfs (`usb_ids.find_tty` / `find_usb`), which is the
identity the device reports about itself and cannot drift.

`uaccess` is needed because a device outside the granted set enumerates normally and then
fails to open without root -- which is indistinguishable from dead gateware, and has
cost time before.

## Why one ID per bitstream

Devices were being found by `/dev/ttyACM*` node number or by newest mtime. Both depend on
plug order and on whatever else is attached; this workstation has eleven `ttyACM` nodes
across four vendors, and an investigation into a silent RISC-V SoC spent hours reading
`/dev/ttyACM1`, an ST-LINK.

Several bitstreams also shared IDs with each other, and two claimed **Apollo's own
`1d50:615c`** -- which made `ApolloDebugger()` capable of opening something that was not
Apollo.

    ./scripts/install_udev.py --check     # show what would change
    sudo ./scripts/install_udev.py        # write and reload
"""

import argparse
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOG = ROOT / "tmp" / "logs" / "install_udev.log"
GENERATED = ROOT / "scripts" / "udev" / "55-cynthion-test.rules"
INSTALLED = Path("/etc/udev/rules.d/55-cynthion-test.rules")

sys.path.insert(0, str(ROOT / "ecp5-test"))

HEADER = """# Test bitstreams built in this workspace: one product ID each.
#
# GENERATED by scripts/install_udev.py from ecp5-test/usb_ids.py.
# Edit that file and re-run, rather than editing this one.
#
# uaccess ONLY. Deliberately no SYMLINK: a symlink is a second name for the device, and a
# second name is another thing that can be stale or point elsewhere. Code resolves devices
# by VID:PID from sysfs, which is the identity the device reports about itself. These
# rules exist purely to make the device openable without root -- a device outside the
# granted set enumerates fine and then fails to open, which looks exactly like dead
# gateware.
"""


def generate():
    import usb_ids

    lines = [HEADER, ""]
    lines.append("# USB devices.")
    for name, (pid, string) in sorted(usb_ids.PRODUCTS.items(), key=lambda kv: kv[1][0]):
        lines.append(
            f'SUBSYSTEM=="usb", ATTR{{idVendor}}=="{usb_ids.VENDOR_ID:04x}", '
            f'ATTR{{idProduct}}=="{pid:04x}", TAG+="uaccess"   # {name}')

    lines.append("")
    lines.append("# The tty interfaces some of them expose. SUBSYSTEM==\"tty\" matches the")
    lines.append("# interface, so vendor/product come from the parent device and need ATTRS.")
    for name, (pid, string) in sorted(usb_ids.PRODUCTS.items(), key=lambda kv: kv[1][0]):
        if "console" in name or "serial" in name:
            lines.append(
                f'SUBSYSTEM=="tty", ATTRS{{idVendor}}=="{usb_ids.VENDOR_ID:04x}", '
                f'ATTRS{{idProduct}}=="{pid:04x}", TAG+="uaccess"   # {name}')
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true",
                        help="generate and compare, without installing")
    args = parser.parse_args()

    LOG.parent.mkdir(parents=True, exist_ok=True)
    with LOG.open("w") as handle:
        def emit(text=""):
            print(text, flush=True)
            handle.write(text + "\n")

        content = generate()
        GENERATED.parent.mkdir(parents=True, exist_ok=True)
        GENERATED.write_text(content)
        emit(f"generated {GENERATED.relative_to(ROOT)}")

        current = INSTALLED.read_text() if INSTALLED.exists() else None
        if current == content:
            emit(f"{INSTALLED} is already up to date")
            return 0

        if args.check:
            emit(f"{INSTALLED} differs" if current else f"{INSTALLED} is not installed")
            emit("run with sudo to install")
            return 1

        try:
            INSTALLED.write_text(content)
        except PermissionError:
            emit(f"cannot write {INSTALLED} -- re-run with sudo")
            return 1
        emit(f"installed {INSTALLED}")

        # Reload and re-trigger, so an already-plugged device picks the rules up without
        # a replug. Without the trigger the rules apply only to the next enumeration,
        # which reads as the change not having worked.
        for cmd in (["udevadm", "control", "--reload-rules"],
                    ["udevadm", "trigger", "--subsystem-match=usb",
                     "--subsystem-match=tty"]):
            result = subprocess.run(cmd, capture_output=True, text=True)
            emit(f"{' '.join(cmd)} -> rc={result.returncode}")

        emit(f"log: {LOG}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
