#!/usr/bin/env python3
#
# Build RV32 firmware for the bring-up SoC.
# SPDX-License-Identifier: BSD-3-Clause

"""
Builds bare-metal RV32 firmware to run on the block-RAM SoC.

Three targets, in increasing order of how much has to work for them to run:

    hello       a few dozen instructions: set the stack, write a string to the
                console register, halt. If this does not print, the fault is
                the CPU, the reset vector or the peripheral -- there is nothing
                else it could be.
    dhrystone   the classic integer benchmark. Needs a working stack, .data and
                .bss, and enough of libc to be interesting.
    coremark    the benchmark the earlier RV32 comparison quoted but never ran
                here. Phase 2 of the bring-up wants this number.

Start with `hello`. Debugging a benchmark harness and a CPU bring-up at the
same time is how a week disappears.

The toolchain is riscv64-linux-gnu-gcc, which targets Linux but produces fine
bare-metal RV32 with -nostdlib and an explicit -march/-mabi. No separate
embedded toolchain is needed.

    ./scripts/riscv_firmware.py
    ./scripts/riscv_firmware.py --target hello
"""

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "tmp" / "riscv_hello"
LOG = ROOT / "tmp" / "logs" / "riscv_firmware.log"

# CoreMark is vendored in the VexiiRiscv submodule rather than fetched.
COREMARK = ROOT / "repos" / "vexiiriscv" / "ext" / "NaxSoftware" / "baremetal" / "coremark"
PORT = ROOT / "ecp5-test" / "riscv" / "coremark_port"

# Enough iterations that the run is dominated by work rather than by startup,
# and few enough that it finishes in seconds on a 60 MHz core.
ITERATIONS = 300

CC = "riscv64-linux-gnu-gcc"
OBJCOPY = "riscv64-linux-gnu-objcopy"
OBJDUMP = "riscv64-linux-gnu-objdump"

# rv32im: multiply is worth having (the ECP5 has DSP blocks, so it is cheap)
# and compressed instructions are omitted to keep the disassembly readable
# during bring-up. ilp32 is the soft-float ABI; there is no FPU.
#
# _zicsr is named explicitly because recent binutils split the CSR
# instructions out of the base ISA; without it `csrw` is an unrecognised
# opcode. The hardware has always had them -- this is a toolchain spelling
# change, not a core feature.
# rv32imac, matching what the CPU generates (--with-rvm --with-rvc --with-rva) and what
# moondancer targets (riscv32imac-unknown-none-elf).
#
# This was rv32im_zicsr, which is a safe subset -- a CPU always runs less than it
# implements -- but it left the C and A extensions completely untested while both are
# enabled in hardware. Moondancer would have been the first code to use them, which is a
# poor place to discover a decode fault. Compressed instructions also shrink the image by
# roughly a quarter, and block RAM is 64 KiB.
ARCH = ["-march=rv32imac_zicsr", "-mabi=ilp32"]

# Must match hello_soc.py. The CPU resets to 0x00000000, so the entry point has
# to be the first thing in the image.
RAM_BASE = 0x00000000
RAM_SIZE = 64 * 1024
# Bit 31 set: below 0x80000000 the data cache absorbs the stores.
# See the note in ecp5-test/riscv/hello_soc.py.
CONSOLE_BASE = 0xf0000000

# The memory-mapped configuration SPI flash and the SPI controller's registers.
# Must match ecp5-test/riscv/vexii_hello_soc.py -- FLASH_BASE, FLASH_CSR_BASE
# and FLASH_TEST_OFFSET there.
FLASH_BASE = 0x10000000
FLASH_CSR_BASE = 0xf0000100
# The offset the firmware reads twice, and benchmarks.
#
# 128 KiB in, which is INSIDE the bitstream, and that is deliberate. 3 MiB was
# tried first and is erased flash: it reads ffffffff, which is the correct
# value there but is indistinguishable from a chip that is not being selected.
# A test whose passing value is also its most common failure value is not a
# test. Bitstream bytes are varied and stable, so a wrong value looks wrong.
#
# Read only. Nothing here writes or erases anything, ever.
FLASH_TEST_OFFSET = 0x00020000

LINKER_SCRIPT = """
/* Generated by scripts/riscv_firmware.py -- do not edit. */
OUTPUT_ARCH(riscv)
ENTRY(_start)

MEMORY {{
    ram (rwx) : ORIGIN = {ram_base:#x}, LENGTH = {ram_size:#x}
}}

SECTIONS {{
    /* .init first: the reset vector is the base of RAM, so _start must be the
       very first instruction in the image. */
    .text : {{
        *(.init)
        *(.text .text.*)
        *(.rodata .rodata.*)
    }} > ram

    .data : {{
        *(.data .data.*)
        *(.sdata .sdata.*)
    }} > ram

    .bss (NOLOAD) : {{
        __bss_start = .;
        *(.bss .bss.*)
        *(.sbss .sbss.*)
        *(COMMON)
        __bss_end = .;
    }} > ram

    /* Stack at the top of RAM, growing down towards .bss. Nothing checks for
       collision -- with 64 KiB and a hello-world there is no realistic risk,
       but a benchmark with deep recursion would need a guard. */
    __stack_top = ORIGIN(ram) + LENGTH(ram);
}}
"""

START_S = """
/* Generated by scripts/riscv_firmware.py -- do not edit. */
    .section .init
    .global _start
_start:
    /* No interrupts, no traps: nothing here enables them, and a trap during
       bring-up would jump somewhere undefined rather than report anything. */
    csrw    mie, zero
    csrw    mip, zero

    la      sp, __stack_top

    /* Zero .bss. C promises it, and a benchmark reading uninitialised counters
       would produce numbers that look plausible and mean nothing. */
    la      t0, __bss_start
    la      t1, __bss_end
1:  bgeu    t0, t1, 2f
    sw      zero, 0(t0)
    addi    t0, t0, 4
    j       1b
2:
    call    main

    /* main returning is not expected. Spin rather than fall into whatever
       follows in memory. */
3:  j       3b
"""

CONSOLE_H = """
/* Generated by scripts/riscv_firmware.py -- do not edit. */
#ifndef CONSOLE_H
#define CONSOLE_H

#define CONSOLE_BASE  {console_base:#x}u

/* Matches ConsolePeripheral in ecp5-test/riscv/hello_soc.py: write a byte to
   `data`, poll `ready` for room. Same shape as the luna_soc UART peripheral,
   so firmware does not care whether the bytes leave over USB or a wire. */
#define CONSOLE_DATA  (*(volatile unsigned char *)(CONSOLE_BASE + 0))
#define CONSOLE_READY (*(volatile unsigned char *)(CONSOLE_BASE + 1))

static inline void putch(char c) {{
    while (!CONSOLE_READY) {{ }}
    CONSOLE_DATA = (unsigned char)c;
}}

static inline void print(const char *s) {{
    while (*s) putch(*s++);
}}

static inline void print_hex(unsigned int v) {{
    for (int shift = 28; shift >= 0; shift -= 4) {{
        unsigned int nibble = (v >> shift) & 0xf;
        putch(nibble < 10 ? ('0' + nibble) : ('a' + nibble - 10));
    }}
}}

#endif
"""

FLASH_H = """
/* Generated by scripts/riscv_firmware.py -- do not edit. */
#ifndef FLASH_H
#define FLASH_H

/* The configuration SPI flash, two ways.

   FLASH_BASE is the memory map: ordinary loads, cached, backed by
   ModalSPIFlashMemoryMap issuing read opcodes. This is the thing under test.

   FLASH_CSR_BASE is luna_soc's SPIController -- a FIFO pair and a shift
   register, able to issue any command at all. It is here only because the
   JEDEC ID (0x9f) is a register read rather than an address read, so no memory
   map can express it.

   NOTHING HERE WRITES OR ERASES. The FPGA bitstream is at flash offset 0 and a
   page program or sector erase would destroy it. The controller path is
   perfectly capable of doing that; the restraint is in this file, not in the
   gateware. */

#define FLASH_BASE      {flash_base:#x}u
#define FLASH_CSR_BASE  {flash_csr_base:#x}u

/* An offset chosen for the read-repeatability check: 3 MiB in, far past a
   ~308 KiB bitstream. Reads are harmless anywhere; this is about reading
   something that is not being changed by anything else. */
#define FLASH_TEST_OFFSET {flash_test_offset:#x}u

/* SPIController register map. Byte offsets from luna_soc's csr.Builder layout
   (addr_width=5, data_width=8), verified against the elaborated memory map
   rather than assumed:

     0x0  phy     length[5:0] | width[9:6] | mask[17:10]   (32-bit access)
     0x4  cs      select[0]
     0x5  status  rx_ready[0], tx_ready[1]
     0x8  data.rx 32 bits, read side  -- reading POPS the RX FIFO
     0xc  data.tx 32 bits, write side

   `data.rx` having a side effect on read is why FLASH_CSR_BASE must be in an
   uncached PMA region. In a cached one the second read returns the first
   read's value out of a cache line, indefinitely. */
#define FLASH_PHY    (*(volatile unsigned int  *)(FLASH_CSR_BASE + 0x0))
#define FLASH_CS     (*(volatile unsigned char *)(FLASH_CSR_BASE + 0x4))
#define FLASH_STATUS (*(volatile unsigned char *)(FLASH_CSR_BASE + 0x5))
#define FLASH_RX     (*(volatile unsigned int  *)(FLASH_CSR_BASE + 0x8))
#define FLASH_TX     (*(volatile unsigned int  *)(FLASH_CSR_BASE + 0xc))

#define FLASH_STATUS_RX_READY 0x1u
#define FLASH_STATUS_TX_READY 0x2u

/* Pack the phy register: transfer length in bits, bus width in lanes, and the
   DQ output-enable mask. mask=1 drives DQ0 only (single-lane send); mask=0
   releases every DQ so the flash can drive them (receive). */
static inline void flash_phy_set(unsigned int len, unsigned int width,
                                 unsigned int mask) {{
    FLASH_PHY = (len & 0x3f) | ((width & 0xf) << 6) | ((mask & 0xff) << 10);
}}

/* Queue one transfer. Does NOT wait for its result.

   SPI is full duplex: every transfer clocks a word out and a word in at the
   same time, so a send and a receive are one operation with different masks,
   and every queued transfer eventually produces an RX word that must be
   consumed or the RX FIFO fills and the controller stalls.

   The wait is on tx_ready -- room in the 16-deep TX FIFO -- not on time. If the
   PHY never drains the FIFO this spins forever, which is the right behaviour
   for bring-up: a silent timeout would turn "the flash is not responding" into
   "the flash returned zero", and those have different causes. */
static inline void flash_push(unsigned int data) {{
    while (!(FLASH_STATUS & FLASH_STATUS_TX_READY)) {{ }}
    FLASH_TX = data;
}}

/* Take one completed transfer's data out of the RX FIFO. */
static inline unsigned int flash_pop(void) {{
    while (!(FLASH_STATUS & FLASH_STATUS_RX_READY)) {{ }}
    return FLASH_RX;
}}

/* Read the JEDEC ID: command 0x9f, then three bytes back. Expect ef4016.

   THE WHOLE SEQUENCE IS QUEUED BEFORE ANY OF IT IS READ BACK, and that is a
   correctness requirement rather than an optimisation.

   luna_soc's SPIController derives chip select from the TX FIFO, not from the
   `cs` register:

       with m.State("RISE"):  m.d.comb += cs.eq(tx_fifo.r_rdy)
       with m.State("FALL"):  m.d.comb += cs.eq(self._cs.f.select.w_data
                                                | tx_fifo.r_rdy)

   `self._cs.f.select` is a csr.action.W field, so `w_data` is live only during
   the cycle of the write strobe -- it is a pulse, not a latch. The `cs` CSR
   therefore cannot hold chip select down across transfers, and CS is
   effectively `tx_fifo.r_rdy` alone.

   So a loop that pushes one transfer and immediately waits for its result
   empties the TX FIFO between every byte, dropping CS and restarting the flash
   each time. The command is accepted and then discarded three times over, and
   the ID reads back as zeros -- which is exactly what the first hardware run
   printed. Queueing all four transfers keeps r_rdy high throughout, so CS stays
   asserted for the whole command as the flash requires.

   The controller shifts MSB-first from the top of a 32-bit word, so an 8-bit
   transfer sends bits 31..24 -- hence the << 24 on the opcode. Received data
   arrives right-aligned. Four transfers is well inside the 16-deep FIFOs. */
static inline unsigned int flash_jedec_id(void) {{
    unsigned int id = 0;

    flash_phy_set(8, 1, 0x1);        /* 8 bits out on DQ0 */
    flash_push(0x9fu << 24);

    flash_phy_set(8, 1, 0x0);        /* 8 bits in, DQ released */
    flash_push(0);
    flash_push(0);
    flash_push(0);

    /* Discard the word clocked in while the command was going out -- the flash
       was not driving yet. */
    (void)flash_pop();

    for (int i = 0; i < 3; i++) {{
        id = (id << 8) | (flash_pop() & 0xff);
    }}

    return id;
}}

/* The memory map, as plain loads. This is what the issue is about: the CPU
   addressing flash the same way it addresses RAM. */
static inline unsigned int flash_read32(unsigned int offset) {{
    return *(volatile unsigned int *)(FLASH_BASE + offset);
}}

#endif
"""

HELLO_C = """
/* Generated by scripts/riscv_firmware.py -- do not edit. */
#include "console.h"
#include "flash.h"

/* Words read per throughput measurement. 256 words is 1 KiB: long enough that
   the command/address/dummy preamble is amortised and the burst-continuation
   path dominates, short enough to fit inside a 32-bit cycle counter at 80 MHz
   with several orders of magnitude to spare. */
#define BENCH_WORDS 256

/* mcycle, the RISC-V cycle counter. Reading it costs one instruction, so it
   can bracket a short read without distorting it -- which is the whole reason
   this measurement belongs on the CPU rather than on the host, where a single
   JTAG register read is ~35 ms against a ~1 us flash read. */
static inline unsigned int cycles(void) {
    unsigned int c;
    __asm__ volatile ("csrr %0, mcycle" : "=r"(c));
    return c;
}

int main(void) {
    print("\\r\\n");
    print("RISC-V on Cynthion: block RAM, USB console.\\r\\n");

    /* Prove arithmetic and memory work, not just the store to a peripheral --
       a CPU that can only write a constant is not obviously executing. */
    volatile unsigned int a = 0x12345678;
    volatile unsigned int b = 0x9abcdef0;
    print("sum  ");
    print_hex(a + b);
    print("\\r\\nprod ");
    print_hex(a * 3);
    print("\\r\\n");

    /* --- The flash, three checks. Raw values, never a bare "OK": a check that
       prints only its verdict hides what it actually saw, and the difference
       between 0xef4016, 0x000000 and 0xffffff is the difference between a
       working chip, a chip that is not being clocked, and a chip that is not
       being selected. */

    /* 1. Identity, through the controller's arbitrary-command path.
          Expect ef4016 -- Winbond, W25Q32, 4 MiB. */
    print("flash jedec  ");
    print_hex(flash_jedec_id());
    print("\\r\\n");

    /* 2. The memory map itself: an ordinary load from FLASH_BASE. Offset 0 is
          the start of the FPGA bitstream, whose first bytes are the ECP5
          preamble -- so this is a value with a known shape, not an opaque one.
          Read only; never written. */
    print("flash @0     ");
    print_hex(flash_read32(0));
    print("\\r\\n");

    /* 3. Repeatability. Two reads of the same offset, printed separately so a
          mismatch shows both values rather than just failing. Equal values
          here mean the sample timing is stable; unequal means it is marginal,
          and the two numbers say how. */
    unsigned int first  = flash_read32(FLASH_TEST_OFFSET);
    unsigned int second = flash_read32(FLASH_TEST_OFFSET);
    print("flash @128K  ");
    print_hex(first);
    print(" ");
    print_hex(second);
    print(first == second ? "  same\\r\\n" : "  DIFFER\\r\\n");

    /* 4. Throughput, as cycles for BENCH_WORDS sequential words. The sum is
          accumulated and printed so the compiler cannot delete the loop, and
          so a run that reads all zeros is distinguishable from one that reads
          real data.

          Sequential and word-by-word on purpose: that is the access pattern a
          CPU executing from flash generates, and it is the pattern the mmap
          controller's burst continuation is built for.

          What this measures is the rate the CPU SEES, not the rate the flash
          sustains. The flash is in a main=1 PMA region, so the D-cache is in
          the path: one miss per cache line fetches the whole line, and the
          remaining words of that line are hits costing a cycle or two. The two
          numbers differ by the line size and that is the point of caching it.
          A raw-flash figure would need the region marked main=0, which is a
          different build. */
    /* `sum` is a plain local, not volatile: the loads inside flash_read32 are
       already volatile so none of them can be elided, and making the
       accumulator volatile too would add a store to memory per iteration and
       measure that instead. It is printed afterwards, which is what keeps the
       whole loop alive. */
    unsigned int sum = 0;
    unsigned int t0 = cycles();
    for (unsigned int i = 0; i < BENCH_WORDS; i++) {
        sum += flash_read32(FLASH_TEST_OFFSET + i * 4);
    }
    unsigned int t1 = cycles();
    volatile unsigned int sink = sum;
    print("flash bench  ");
    print_hex(t1 - t0);
    print(" cycles / ");
    print_hex(BENCH_WORDS);
    print(" words, sum ");
    print_hex(sink);
    print("\\r\\n");

    unsigned int count = 0;
    for (;;) {
        print("tick ");
        print_hex(count++);
        print("\\r\\n");
        /* Roughly a second at 60 MHz, so the stream is readable rather than a
           blur. Not calibrated -- it only has to be visibly periodic. */
        for (volatile unsigned int i = 0; i < 6000000; i++) { }
    }
    return 0;
}
"""


def emit(handle, text=""):
    print(text, flush=True)
    handle.write(text + "\n")
    handle.flush()


def write_common(work):
    """Write the files every target shares."""
    (work / "link.ld").write_text(
        LINKER_SCRIPT.format(ram_base=RAM_BASE, ram_size=RAM_SIZE))
    (work / "start.S").write_text(START_S)
    (work / "console.h").write_text(
        CONSOLE_H.format(console_base=CONSOLE_BASE))
    (work / "flash.h").write_text(
        FLASH_H.format(flash_base=FLASH_BASE,
                       flash_csr_base=FLASH_CSR_BASE,
                       flash_test_offset=FLASH_TEST_OFFSET))


def build(target, work, handle):
    """Compile, link, and emit a raw binary."""
    write_common(work)

    extra_flags = []
    if target == "hello":
        (work / "main.c").write_text(HELLO_C)
        sources = [str(work / "start.S"), str(work / "main.c")]
    elif target == "softfloat":
        # Measures what floating point costs when libgcc emulates it. Uses the
        # same console.h as hello, so it needs no CoreMark machinery.
        sources = [str(work / "start.S"),
                   str(PORT / "softfloat_bench.c")]
        extra_flags = [f"-I{work}"]
    elif target == "coremark":
        if not COREMARK.exists():
            emit(handle, f"CoreMark sources not found at {COREMARK}")
            emit(handle, "  They are vendored in the VexiiRiscv submodule; run")
            emit(handle, "  git submodule update --init --recursive")
            return None
        sources = [str(work / "start.S"),
                   str(PORT / "core_portme.c")]
        sources += [str(COREMARK / f) for f in
                    ("core_main.c", "core_list_join.c", "core_matrix.c",
                     "core_state.c", "core_util.c")]
        # ITERATIONS is fixed rather than auto-scaled: CoreMark normally grows
        # the count until a run takes 10 s, which needs a wall clock. Ticks
        # here are CPU cycles, and a fixed count makes runs directly
        # comparable between configurations.
        extra_flags = [f"-I{COREMARK}", f"-I{PORT}",
                       "-DPERFORMANCE_RUN=1", f"-DITERATIONS={ITERATIONS}",
                       "-DMAIN_HAS_NOARGC=1", '-DCOMPILER_FLAGS="-O2"',
                       "-DSEED_METHOD=SEED_VOLATILE"]
    else:
        emit(handle, f"{target}: not vendored.")
        emit(handle, "  Dhrystone needs its sources fetched. CoreMark is "
                     "available as")
        emit(handle, "  --target coremark.")
        return None

    elf = work / f"{target}.elf"
    # -O2 for benchmarks: CoreMark measures the compiler as much as the core,
    # and -Os would understate every configuration equally but pointlessly.
    optimisation = "-O2" if target in ("coremark", "softfloat") else "-Os"
    command = [CC, *ARCH, optimisation, "-g",
               "-nostdlib", "-nostartfiles", "-ffreestanding",
               "-fno-builtin", "-Wall",
               f"-I{work}", *extra_flags,
               "-T", str(work / "link.ld"),
               "-o", str(elf),
               *sources,
               # libgcc, not a libc: it supplies the soft-float helpers
               # (__divdf3, __floatunsidf) that CoreMark's own reporting code
               # needs on a core with no FPU. -nostdlib excludes it, and
               # patching upstream source to avoid double arithmetic would be
               # worse than linking the runtime that exists for this.
               "-lgcc"]

    result = subprocess.run(command, capture_output=True, text=True)
    if result.returncode != 0:
        emit(handle, "compile failed:")
        for line in (result.stderr or "").strip().splitlines()[:15]:
            emit(handle, f"    {line}")
        return None
    for line in (result.stderr or "").strip().splitlines():
        emit(handle, f"    warning: {line}")

    binary = work / f"{target}.bin"
    subprocess.run([OBJCOPY, "-O", "binary", str(elf), str(binary)],
                   check=True)

    listing = work / f"{target}.lst"
    disassembly = subprocess.run([OBJDUMP, "-d", str(elf)],
                                 capture_output=True, text=True)
    listing.write_text(disassembly.stdout)

    return binary, elf


def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--target", default="hello",
                        choices=["hello", "dhrystone", "coremark",
                                 "softfloat"])
    args = parser.parse_args()

    for tool in (CC, OBJCOPY, OBJDUMP):
        if shutil.which(tool) is None:
            print(f"{tool} not found")
            return 1

    OUT.mkdir(parents=True, exist_ok=True)
    LOG.parent.mkdir(parents=True, exist_ok=True)

    with LOG.open("w") as handle:
        emit(handle, f"building {args.target} for rv32im/ilp32")
        emit(handle)

        built = build(args.target, OUT, handle)
        if built is None:
            return 1
        binary, elf = built

        size = binary.stat().st_size
        emit(handle, f"  {binary.name}: {size} bytes "
                     f"({100 * size / RAM_SIZE:.1f}% of {RAM_SIZE // 1024} KiB "
                     f"block RAM)")

        # The reset vector is the base of RAM, so whatever is at offset 0 runs
        # first. Checking it is _start catches a linker script that reordered
        # sections -- which fails silently and looks like a dead CPU.
        entry = subprocess.run([OBJDUMP, "-d", "--start-address=0",
                                "--stop-address=8", str(elf)],
                               capture_output=True, text=True).stdout
        emit(handle)
        emit(handle, "  first instructions at the reset vector:")
        for line in entry.splitlines():
            if ":\t" in line:
                emit(handle, f"    {line.strip()}")

        emit(handle)
        emit(handle, f"  disassembly: {elf.with_suffix('.lst')}")
        emit(handle, f"  log: {LOG}")
        emit(handle)
        emit(handle, "next: ./ecp5-test/riscv/hello_soc.py --build --program")

    return 0


if __name__ == "__main__":
    sys.exit(main())
