#!/usr/bin/env python3
#
# Build RV32 firmware for the bring-up SoC.
# SPDX-License-Identifier: BSD-3-Clause

"""
Builds bare-metal RV32 firmware to run on the block-RAM SoC.

Three targets, in increasing order of how much has to work for them to run:

    hello       a few dozen instructions: set the stack, write a string to the
                console register, halt. If this does not print, the fault is
                the CPU, the reset vector or the peripheral -- there is nothing
                else it could be.
    dhrystone   the classic integer benchmark. Needs a working stack, .data and
                .bss, and enough of libc to be interesting.
    coremark    the benchmark the earlier RV32 comparison quoted but never ran
                here. Phase 2 of the bring-up wants this number.

Start with `hello`. Debugging a benchmark harness and a CPU bring-up at the
same time is how a week disappears.

The toolchain is riscv64-linux-gnu-gcc, which targets Linux but produces fine
bare-metal RV32 with -nostdlib and an explicit -march/-mabi. No separate
embedded toolchain is needed.

    ./scripts/riscv_firmware.py
    ./scripts/riscv_firmware.py --target hello
"""

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "tmp" / "riscv_hello"
LOG = ROOT / "tmp" / "logs" / "riscv_firmware.log"

CC = "riscv64-linux-gnu-gcc"
OBJCOPY = "riscv64-linux-gnu-objcopy"
OBJDUMP = "riscv64-linux-gnu-objdump"

# rv32im: multiply is worth having (the ECP5 has DSP blocks, so it is cheap)
# and compressed instructions are omitted to keep the disassembly readable
# during bring-up. ilp32 is the soft-float ABI; there is no FPU.
#
# _zicsr is named explicitly because recent binutils split the CSR
# instructions out of the base ISA; without it `csrw` is an unrecognised
# opcode. The hardware has always had them -- this is a toolchain spelling
# change, not a core feature.
ARCH = ["-march=rv32im_zicsr", "-mabi=ilp32"]

# Must match hello_soc.py. The CPU resets to 0x00000000, so the entry point has
# to be the first thing in the image.
RAM_BASE = 0x00000000
RAM_SIZE = 64 * 1024
# Bit 31 set: below 0x80000000 the data cache absorbs the stores.
# See the note in ecp5-test/riscv/hello_soc.py.
CONSOLE_BASE = 0xf0000000

LINKER_SCRIPT = """
/* Generated by scripts/riscv_firmware.py -- do not edit. */
OUTPUT_ARCH(riscv)
ENTRY(_start)

MEMORY {{
    ram (rwx) : ORIGIN = {ram_base:#x}, LENGTH = {ram_size:#x}
}}

SECTIONS {{
    /* .init first: the reset vector is the base of RAM, so _start must be the
       very first instruction in the image. */
    .text : {{
        *(.init)
        *(.text .text.*)
        *(.rodata .rodata.*)
    }} > ram

    .data : {{
        *(.data .data.*)
        *(.sdata .sdata.*)
    }} > ram

    .bss (NOLOAD) : {{
        __bss_start = .;
        *(.bss .bss.*)
        *(.sbss .sbss.*)
        *(COMMON)
        __bss_end = .;
    }} > ram

    /* Stack at the top of RAM, growing down towards .bss. Nothing checks for
       collision -- with 64 KiB and a hello-world there is no realistic risk,
       but a benchmark with deep recursion would need a guard. */
    __stack_top = ORIGIN(ram) + LENGTH(ram);
}}
"""

START_S = """
/* Generated by scripts/riscv_firmware.py -- do not edit. */
    .section .init
    .global _start
_start:
    /* No interrupts, no traps: nothing here enables them, and a trap during
       bring-up would jump somewhere undefined rather than report anything. */
    csrw    mie, zero
    csrw    mip, zero

    la      sp, __stack_top

    /* Zero .bss. C promises it, and a benchmark reading uninitialised counters
       would produce numbers that look plausible and mean nothing. */
    la      t0, __bss_start
    la      t1, __bss_end
1:  bgeu    t0, t1, 2f
    sw      zero, 0(t0)
    addi    t0, t0, 4
    j       1b
2:
    call    main

    /* main returning is not expected. Spin rather than fall into whatever
       follows in memory. */
3:  j       3b
"""

CONSOLE_H = """
/* Generated by scripts/riscv_firmware.py -- do not edit. */
#ifndef CONSOLE_H
#define CONSOLE_H

#define CONSOLE_BASE  {console_base:#x}u

/* Matches ConsolePeripheral in ecp5-test/riscv/hello_soc.py: write a byte to
   `data`, poll `ready` for room. Same shape as the luna_soc UART peripheral,
   so firmware does not care whether the bytes leave over USB or a wire. */
#define CONSOLE_DATA  (*(volatile unsigned char *)(CONSOLE_BASE + 0))
#define CONSOLE_READY (*(volatile unsigned char *)(CONSOLE_BASE + 1))

static inline void putch(char c) {{
    while (!CONSOLE_READY) {{ }}
    CONSOLE_DATA = (unsigned char)c;
}}

static inline void print(const char *s) {{
    while (*s) putch(*s++);
}}

static inline void print_hex(unsigned int v) {{
    for (int shift = 28; shift >= 0; shift -= 4) {{
        unsigned int nibble = (v >> shift) & 0xf;
        putch(nibble < 10 ? ('0' + nibble) : ('a' + nibble - 10));
    }}
}}

#endif
"""

HELLO_C = """
/* Generated by scripts/riscv_firmware.py -- do not edit. */
#include "console.h"

int main(void) {
    print("\\r\\n");
    print("RISC-V on Cynthion: block RAM, USB console.\\r\\n");

    /* Prove arithmetic and memory work, not just the store to a peripheral --
       a CPU that can only write a constant is not obviously executing. */
    volatile unsigned int a = 0x12345678;
    volatile unsigned int b = 0x9abcdef0;
    print("sum  ");
    print_hex(a + b);
    print("\\r\\nprod ");
    print_hex(a * 3);
    print("\\r\\n");

    unsigned int count = 0;
    for (;;) {
        print("tick ");
        print_hex(count++);
        print("\\r\\n");
        /* Roughly a second at 60 MHz, so the stream is readable rather than a
           blur. Not calibrated -- it only has to be visibly periodic. */
        for (volatile unsigned int i = 0; i < 6000000; i++) { }
    }
    return 0;
}
"""


def emit(handle, text=""):
    print(text, flush=True)
    handle.write(text + "\n")
    handle.flush()


def write_common(work):
    """Write the files every target shares."""
    (work / "link.ld").write_text(
        LINKER_SCRIPT.format(ram_base=RAM_BASE, ram_size=RAM_SIZE))
    (work / "start.S").write_text(START_S)
    (work / "console.h").write_text(
        CONSOLE_H.format(console_base=CONSOLE_BASE))


def build(target, work, handle):
    """Compile, link, and emit a raw binary."""
    write_common(work)

    if target == "hello":
        (work / "main.c").write_text(HELLO_C)
        sources = ["start.S", "main.c"]
    else:
        emit(handle, f"{target}: not vendored yet.")
        emit(handle, "  Dhrystone and CoreMark need their sources fetched and "
                     "a timing")
        emit(handle, "  hook wired to a cycle counter. Bring `hello` up first "
                     "-- until the")
        emit(handle, "  CPU is known to execute and print, a benchmark that "
                     "produces no")
        emit(handle, "  output is indistinguishable from a CPU that never "
                     "started.")
        return None

    elf = work / f"{target}.elf"
    command = [CC, *ARCH, "-Os", "-g",
               "-nostdlib", "-nostartfiles", "-ffreestanding",
               "-fno-builtin", "-Wall", "-Wextra",
               f"-I{work}",
               "-T", str(work / "link.ld"),
               "-o", str(elf),
               *[str(work / s) for s in sources]]

    result = subprocess.run(command, capture_output=True, text=True)
    if result.returncode != 0:
        emit(handle, "compile failed:")
        for line in (result.stderr or "").strip().splitlines()[:15]:
            emit(handle, f"    {line}")
        return None
    for line in (result.stderr or "").strip().splitlines():
        emit(handle, f"    warning: {line}")

    binary = work / f"{target}.bin"
    subprocess.run([OBJCOPY, "-O", "binary", str(elf), str(binary)],
                   check=True)

    listing = work / f"{target}.lst"
    disassembly = subprocess.run([OBJDUMP, "-d", str(elf)],
                                 capture_output=True, text=True)
    listing.write_text(disassembly.stdout)

    return binary, elf


def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--target", default="hello",
                        choices=["hello", "dhrystone", "coremark"])
    args = parser.parse_args()

    for tool in (CC, OBJCOPY, OBJDUMP):
        if shutil.which(tool) is None:
            print(f"{tool} not found")
            return 1

    OUT.mkdir(parents=True, exist_ok=True)
    LOG.parent.mkdir(parents=True, exist_ok=True)

    with LOG.open("w") as handle:
        emit(handle, f"building {args.target} for rv32im/ilp32")
        emit(handle)

        built = build(args.target, OUT, handle)
        if built is None:
            return 1
        binary, elf = built

        size = binary.stat().st_size
        emit(handle, f"  {binary.name}: {size} bytes "
                     f"({100 * size / RAM_SIZE:.1f}% of {RAM_SIZE // 1024} KiB "
                     f"block RAM)")

        # The reset vector is the base of RAM, so whatever is at offset 0 runs
        # first. Checking it is _start catches a linker script that reordered
        # sections -- which fails silently and looks like a dead CPU.
        entry = subprocess.run([OBJDUMP, "-d", "--start-address=0",
                                "--stop-address=8", str(elf)],
                               capture_output=True, text=True).stdout
        emit(handle)
        emit(handle, "  first instructions at the reset vector:")
        for line in entry.splitlines():
            if ":\t" in line:
                emit(handle, f"    {line.strip()}")

        emit(handle)
        emit(handle, f"  disassembly: {elf.with_suffix('.lst')}")
        emit(handle, f"  log: {LOG}")
        emit(handle)
        emit(handle, "next: ./ecp5-test/riscv/hello_soc.py --build --program")

    return 0


if __name__ == "__main__":
    sys.exit(main())
