#!/usr/bin/env python3
#
# Firmware that proves the CPU runs before it touches any peripheral.
# SPDX-License-Identifier: BSD-3-Clause

"""
Builds a probe image that writes progress markers to block RAM, readable over
JTAG, so "the CPU is dead" and "the console is unreachable" stop being the same
observation.

The hello firmware calls `print()` as its first statement, and `print()` spins
on `CONSOLE_READY`. If that poll never passes, the CPU parks in a loop having
produced no side effect anywhere -- which looks exactly like a CPU that never
started. Both SoCs currently present that way and the cause is not established.

This image writes a marker to a fixed RAM address at each stage, so a JTAG read
of block RAM says how far execution got with no USB involvement at all:

    0x0000BEEF  reset vector reached, register file works
    0x0000CAFE  arithmetic and RAM read/write work
    0x0000F00D  the console's READY bit read back as high
    0x0000DEAD  READY never went high (written after a bounded spin)

The last two are the discriminator. A bounded spin is used deliberately: an
unbounded one cannot distinguish "not ready yet" from "never ready", and that
ambiguity is the whole reason this probe exists.

    ./scripts/riscv_probe_firmware.py
    ./scripts/riscv_probe_firmware.py --marker-base 0x100
"""

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "tmp" / "riscv_probe"
LOG = ROOT / "tmp" / "logs" / "riscv_probe_firmware.log"

# Markers land near the top of the 64 KiB block RAM, clear of code and of the
# stack, which the linker places at the very top.
MARKER_BASE = 0xF000
CONSOLE_BASE = 0xF0000000

# How long to wait for READY before declaring it stuck. At 60 MHz this is a few
# milliseconds -- far longer than an empty FIFO needs to report space, and short
# enough that the marker gets written while someone is still watching.
READY_SPIN_LIMIT = 200000

SOURCE = """
/* Generated by scripts/riscv_probe_firmware.py -- do not edit. */

#define MARKER(n)  (*(volatile unsigned int *)({marker_base:#x}u + ((n) * 4u)))
#define CONSOLE_READY (*(volatile unsigned char *)({console_base:#x}u + 1u))
#define CONSOLE_DATA  (*(volatile unsigned char *)({console_base:#x}u + 0u))

void _start(void) {{
    /* Set up a stack before anything else. Top of the 64 KiB block RAM. */
    __asm__ volatile("li sp, 0x10000");

    /* Stage 1: we are executing and can write RAM at all. */
    MARKER(0) = 0x0000BEEFu;

    /* Stage 2: arithmetic and a RAM round-trip, so a CPU that can only store a
       constant is not mistaken for a working one. */
    volatile unsigned int a = 0x12345678u;
    volatile unsigned int b = 0x9abcdef0u;
    unsigned int sum = a + b;
    MARKER(1) = 0x0000CAFEu;
    MARKER(2) = sum;

    /* Stage 3: can we even READ the peripheral? This is the discriminator.
       A bounded spin, because an unbounded one cannot tell "not yet" from
       "never" -- which is exactly the ambiguity being resolved. */
    unsigned int spins = 0;
    unsigned char ready = 0;
    while (spins < {spin_limit}u) {{
        ready = CONSOLE_READY;
        if (ready) break;
        spins++;
    }}

    MARKER(3) = ready ? 0x0000F00Du : 0x0000DEADu;
    MARKER(4) = spins;
    MARKER(5) = (unsigned int)ready;

    /* Stage 4: only now attempt a write, and record that we survived it. A
       store to an unacknowledged bus stalls forever, so if MARKER(6) is absent
       while MARKER(3) says F00D, the write path is the fault and the read path
       is not. */
    CONSOLE_DATA = 'X';
    MARKER(6) = 0x00005A5Au;

    for (;;) {{ }}
}}
"""

LINKER = """
/* Generated -- do not edit. */
MEMORY {{ ram (rwx) : ORIGIN = 0x00000000, LENGTH = {ram_size} }}
SECTIONS {{
    .text : {{ *(.text*) }} > ram
    .data : {{ *(.data*) *(.rodata*) *(.bss*) *(COMMON) }} > ram
}}
"""


def tool(name):
    """Find a RISC-V cross tool, trying the usual triples."""
    for prefix in ("riscv64-unknown-elf-", "riscv32-unknown-elf-",
                   "riscv64-linux-gnu-", "riscv-none-elf-"):
        found = shutil.which(prefix + name)
        if found:
            return found
    return None


def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--marker-base", type=lambda v: int(v, 0),
                        default=MARKER_BASE)
    parser.add_argument("--ram-size", type=lambda v: int(v, 0),
                        default=64 * 1024)
    args = parser.parse_args()

    gcc, objcopy = tool("gcc"), tool("objcopy")
    if not gcc or not objcopy:
        print("no RISC-V cross compiler on PATH")
        return 1

    OUT.mkdir(parents=True, exist_ok=True)
    LOG.parent.mkdir(parents=True, exist_ok=True)

    source = OUT / "probe.c"
    source.write_text(SOURCE.format(marker_base=args.marker_base,
                                    console_base=CONSOLE_BASE,
                                    spin_limit=READY_SPIN_LIMIT))
    script = OUT / "probe.ld"
    script.write_text(LINKER.format(ram_size=args.ram_size))

    elf, binary = OUT / "probe.elf", OUT / "probe.bin"

    # -march without the A extension: this probe does no atomics, and the
    # cacheless bridge asserts !withAmo anyway.
    compile_command = [
        gcc, "-march=rv32im_zicsr", "-mabi=ilp32", "-Os",
        "-nostdlib", "-ffreestanding", "-fno-builtin",
        "-T", str(script), "-o", str(elf), str(source),
    ]

    with LOG.open("w") as handle:
        def emit(text):
            print(text, flush=True)
            handle.write(text + "\n")

        emit(f"marker base {args.marker_base:#x}, spin limit {READY_SPIN_LIMIT}")
        result = subprocess.run(compile_command, capture_output=True, text=True)
        if result.returncode != 0:
            emit("compile failed:")
            emit(result.stderr.strip()[:1200])
            return 1

        subprocess.run([objcopy, "-O", "binary", str(elf), str(binary)],
                       check=True)
        size = binary.stat().st_size
        emit(f"built {binary.relative_to(ROOT)}, {size} bytes")
        emit("")
        emit("markers, once running:")
        for index, meaning in enumerate((
                "0x0000BEEF  executing, RAM writable",
                "0x0000CAFE  arithmetic and RAM round-trip work",
                "            the computed sum (expect 0xacf13568)",
                "0x0000F00D / 0x0000DEAD  console READY high / stuck",
                "            spin count before READY went high",
                "            the raw READY byte",
                "0x00005A5A  survived a console write")):
            emit(f"  {args.marker_base + index * 4:#06x}  {meaning}")
        emit(f"log: {LOG}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
