//! `map` and `pmod` -- what this SoC decodes, and what is on the connectors.
//!
//! Both render `cynthion_soc_pac::hardware`, generated by the same walk of the
//! SoC's own memory map that produces every address the firmware uses. So the
//! board cannot report a map it is not running.
//!
//! Moved out of `main.rs` unchanged (#296).

use core::fmt::Write;

use crate::uart::Uart;

/// `map` -- every peripheral window this SoC decodes.
///
/// From `cynthion_soc_pac::hardware`, generated by the same walk of the SoC's own
/// memory map that produces every address the firmware uses. So the board cannot
/// report a map it is not running.
///
/// **It issues no bus traffic.** Reading some registers has side effects -- the
/// SPI controller's `data` pops the RX FIFO, the FUSB302B's interrupt registers
/// are read-to-clear -- so a command that dumped live values would destroy the
/// state someone was inspecting, and the damage would surface somewhere else.
/// This prints the description only. Live values are a separate decision.
pub(crate) fn map_command(uart: &mut Uart) {
    #[cfg(not(feature = "qemu"))]
    {
        let _ = writeln!(uart, "peripheral            base      size  regs");
        for entry in cynthion_soc_pac::hardware::PERIPHERALS {
            let _ = writeln!(
                uart,
                "{:20} {:08x} {:9x} {:5}",
                entry.name, entry.base, entry.size, entry.registers
            );
        }
    }
    #[cfg(feature = "qemu")]
    let _ = uart.write_str("no generated peripheral map on this target\n");
}

/// `pmod` -- the physical connectors, and whether anything has claimed a pin.
///
/// The `claimed` column is the reason this is generated rather than written down:
/// it is computed from what `elaborate()` actually requested, so it cannot say a
/// pin is free when something already took it. Every pin currently reads free --
/// the SoC requests neither PMOD nor the mezzanine.
///
/// Pins absent from a connector's map are its power pins: on a PMOD, 5 and 11 are
/// ground and 6 and 12 are 3V3.
pub(crate) fn pmod_command(uart: &mut Uart) {
    #[cfg(not(feature = "qemu"))]
    {
        let _ = writeln!(uart, "connector  pin  ball  resource        state");
        for entry in cynthion_soc_pac::hardware::CONNECTOR_PINS {
            let _ = writeln!(
                uart,
                "{:10} {:>3}  {:5} {:15} {}",
                entry.connector,
                entry.pin,
                entry.ball,
                if entry.resource.is_empty() {
                    "--"
                } else {
                    entry.resource
                },
                if entry.claimed { "claimed" } else { "free" }
            );
        }
    }
    #[cfg(feature = "qemu")]
    let _ = uart.write_str("no connectors on this target\n");
}

