// Generated by scripts/cpu_matrix.py -- timing harness only.
module fmax_top (
  input  wire clk,
  input  wire rst,
  input  wire din,
  output wire dout
);
  reg [238:0] stim;
  wire [292:0] obs;
  reg [292:0] obs_r;
  always @(posedge clk) stim <= {stim[237:0], din};
  always @(posedge clk) obs_r <= obs;
  reg [18:0] red;
  always @(posedge clk) red[0] <= ^obs_r[15:0];
  always @(posedge clk) red[1] <= ^obs_r[31:16];
  always @(posedge clk) red[2] <= ^obs_r[47:32];
  always @(posedge clk) red[3] <= ^obs_r[63:48];
  always @(posedge clk) red[4] <= ^obs_r[79:64];
  always @(posedge clk) red[5] <= ^obs_r[95:80];
  always @(posedge clk) red[6] <= ^obs_r[111:96];
  always @(posedge clk) red[7] <= ^obs_r[127:112];
  always @(posedge clk) red[8] <= ^obs_r[143:128];
  always @(posedge clk) red[9] <= ^obs_r[159:144];
  always @(posedge clk) red[10] <= ^obs_r[175:160];
  always @(posedge clk) red[11] <= ^obs_r[191:176];
  always @(posedge clk) red[12] <= ^obs_r[207:192];
  always @(posedge clk) red[13] <= ^obs_r[223:208];
  always @(posedge clk) red[14] <= ^obs_r[239:224];
  always @(posedge clk) red[15] <= ^obs_r[255:240];
  always @(posedge clk) red[16] <= ^obs_r[271:256];
  always @(posedge clk) red[17] <= ^obs_r[287:272];
  always @(posedge clk) red[18] <= ^obs_r[292:288];
  reg dout_r;
  always @(posedge clk) dout_r <= ^red;
  assign dout = dout_r;
  VexiiRiscv dut (
    .clk(clk),
    .reset(rst),
    .FetchL1Plugin_logic_bus_cmd_ready(stim[0]),
    .FetchL1Plugin_logic_bus_rsp_valid(stim[1]),
    .FetchL1Plugin_logic_bus_rsp_payload_data(stim[33:2]),
    .FetchL1Plugin_logic_bus_rsp_payload_error(stim[34]),
    .LsuL1Plugin_logic_bus_read_cmd_ready(stim[35]),
    .LsuL1Plugin_logic_bus_read_rsp_valid(stim[36]),
    .LsuL1Plugin_logic_bus_read_rsp_payload_data(stim[100:37]),
    .LsuL1Plugin_logic_bus_read_rsp_payload_error(stim[101]),
    .LsuL1Plugin_logic_bus_write_cmd_ready(stim[102]),
    .LsuL1Plugin_logic_bus_write_rsp_valid(stim[103]),
    .LsuL1Plugin_logic_bus_write_rsp_payload_error(stim[104]),
    .PrivilegedPlugin_logic_rdtime(stim[168:105]),
    .PrivilegedPlugin_logic_harts_0_int_m_timer(stim[169]),
    .PrivilegedPlugin_logic_harts_0_int_m_software(stim[170]),
    .PrivilegedPlugin_logic_harts_0_int_m_external(stim[171]),
    .LsuPlugin_logic_bus_cmd_ready(stim[172]),
    .LsuPlugin_logic_bus_rsp_valid(stim[173]),
    .LsuPlugin_logic_bus_rsp_payload_error(stim[174]),
    .LsuPlugin_logic_bus_rsp_payload_data(stim[238:175]),
    .FetchL1Plugin_logic_bus_cmd_valid(obs[0]),
    .FetchL1Plugin_logic_bus_cmd_payload_address(obs[32:1]),
    .FetchL1Plugin_logic_bus_cmd_payload_io(obs[33]),
    .FetchL1Plugin_logic_bus_rsp_ready(obs[34]),
    .LsuL1Plugin_logic_bus_read_cmd_valid(obs[35]),
    .LsuL1Plugin_logic_bus_read_cmd_payload_address(obs[67:36]),
    .LsuL1Plugin_logic_bus_read_rsp_ready(obs[68]),
    .LsuL1Plugin_logic_bus_write_cmd_valid(obs[69]),
    .LsuL1Plugin_logic_bus_write_cmd_payload_last(obs[70]),
    .LsuL1Plugin_logic_bus_write_cmd_payload_fragment_address(obs[102:71]),
    .LsuL1Plugin_logic_bus_write_cmd_payload_fragment_data(obs[166:103]),
    .LsuPlugin_logic_bus_cmd_valid(obs[167]),
    .LsuPlugin_logic_bus_cmd_payload_write(obs[168]),
    .LsuPlugin_logic_bus_cmd_payload_address(obs[200:169]),
    .LsuPlugin_logic_bus_cmd_payload_data(obs[264:201]),
    .LsuPlugin_logic_bus_cmd_payload_size(obs[266:265]),
    .LsuPlugin_logic_bus_cmd_payload_mask(obs[274:267]),
    .LsuPlugin_logic_bus_cmd_payload_io(obs[275]),
    .LsuPlugin_logic_bus_cmd_payload_fromHart(obs[276]),
    .LsuPlugin_logic_bus_cmd_payload_uopId(obs[292:277])
  );
endmodule
