// Generated by scripts/cpu_matrix.py -- timing harness only.
module fmax_top (
  input  wire clk,
  input  wire rst,
  input  wire din,
  output wire dout
);
  reg [139:0] stim;
  wire [130:0] obs;
  reg [130:0] obs_r;
  always @(posedge clk) stim <= {stim[138:0], din};
  always @(posedge clk) obs_r <= obs;
  reg [8:0] red;
  always @(posedge clk) red[0] <= ^obs_r[15:0];
  always @(posedge clk) red[1] <= ^obs_r[31:16];
  always @(posedge clk) red[2] <= ^obs_r[47:32];
  always @(posedge clk) red[3] <= ^obs_r[63:48];
  always @(posedge clk) red[4] <= ^obs_r[79:64];
  always @(posedge clk) red[5] <= ^obs_r[95:80];
  always @(posedge clk) red[6] <= ^obs_r[111:96];
  always @(posedge clk) red[7] <= ^obs_r[127:112];
  always @(posedge clk) red[8] <= ^obs_r[130:128];
  reg dout_r;
  always @(posedge clk) dout_r <= ^red;
  assign dout = dout_r;
  VexiiRiscv dut (
    .clk(clk),
    .reset(rst),
    .PrivilegedPlugin_logic_rdtime(stim[63:0]),
    .PrivilegedPlugin_logic_harts_0_int_m_timer(stim[64]),
    .PrivilegedPlugin_logic_harts_0_int_m_software(stim[65]),
    .PrivilegedPlugin_logic_harts_0_int_m_external(stim[66]),
    .FetchCachelessPlugin_logic_bus_cmd_ready(stim[67]),
    .FetchCachelessPlugin_logic_bus_rsp_valid(stim[68]),
    .FetchCachelessPlugin_logic_bus_rsp_payload_id(stim[69]),
    .FetchCachelessPlugin_logic_bus_rsp_payload_error(stim[70]),
    .FetchCachelessPlugin_logic_bus_rsp_payload_word(stim[102:71]),
    .LsuCachelessPlugin_logic_bus_cmd_ready(stim[103]),
    .LsuCachelessPlugin_logic_bus_rsp_valid(stim[104]),
    .LsuCachelessPlugin_logic_bus_rsp_payload_id(stim[105]),
    .LsuCachelessPlugin_logic_bus_rsp_payload_error(stim[106]),
    .LsuCachelessPlugin_logic_bus_rsp_payload_data(stim[138:107]),
    .LsuCachelessPlugin_logic_bus_rsp_payload_scMiss(stim[139]),
    .FetchCachelessPlugin_logic_bus_cmd_valid(obs[0]),
    .FetchCachelessPlugin_logic_bus_cmd_payload_id(obs[1]),
    .FetchCachelessPlugin_logic_bus_cmd_payload_address(obs[33:2]),
    .LsuCachelessPlugin_logic_bus_cmd_valid(obs[34]),
    .LsuCachelessPlugin_logic_bus_cmd_payload_id(obs[35]),
    .LsuCachelessPlugin_logic_bus_cmd_payload_write(obs[36]),
    .LsuCachelessPlugin_logic_bus_cmd_payload_address(obs[68:37]),
    .LsuCachelessPlugin_logic_bus_cmd_payload_data(obs[100:69]),
    .LsuCachelessPlugin_logic_bus_cmd_payload_size(obs[102:101]),
    .LsuCachelessPlugin_logic_bus_cmd_payload_mask(obs[106:103]),
    .LsuCachelessPlugin_logic_bus_cmd_payload_amoEnable(obs[107]),
    .LsuCachelessPlugin_logic_bus_cmd_payload_amoOp(obs[112:108]),
    .LsuCachelessPlugin_logic_bus_cmd_payload_io(obs[113]),
    .LsuCachelessPlugin_logic_bus_cmd_payload_fromHart(obs[114]),
    .LsuCachelessPlugin_logic_bus_cmd_payload_uopId(obs[130:115])
  );
endmodule
