// Generated by scripts/cpu_matrix.py -- timing harness only.
module fmax_top (
  input  wire clk,
  input  wire rst,
  input  wire din,
  input  wire EmbeddedRiscvJtag_logic_jtagInstruction_tck,
  output wire dout
);
  reg [239:0] stim;
  wire [291:0] obs;
  reg [291:0] obs_r;
  always @(posedge clk) stim <= {stim[238:0], din};
  always @(posedge clk) obs_r <= obs;
  reg [18:0] red;
  always @(posedge clk) red[0] <= ^obs_r[15:0];
  always @(posedge clk) red[1] <= ^obs_r[31:16];
  always @(posedge clk) red[2] <= ^obs_r[47:32];
  always @(posedge clk) red[3] <= ^obs_r[63:48];
  always @(posedge clk) red[4] <= ^obs_r[79:64];
  always @(posedge clk) red[5] <= ^obs_r[95:80];
  always @(posedge clk) red[6] <= ^obs_r[111:96];
  always @(posedge clk) red[7] <= ^obs_r[127:112];
  always @(posedge clk) red[8] <= ^obs_r[143:128];
  always @(posedge clk) red[9] <= ^obs_r[159:144];
  always @(posedge clk) red[10] <= ^obs_r[175:160];
  always @(posedge clk) red[11] <= ^obs_r[191:176];
  always @(posedge clk) red[12] <= ^obs_r[207:192];
  always @(posedge clk) red[13] <= ^obs_r[223:208];
  always @(posedge clk) red[14] <= ^obs_r[239:224];
  always @(posedge clk) red[15] <= ^obs_r[255:240];
  always @(posedge clk) red[16] <= ^obs_r[271:256];
  always @(posedge clk) red[17] <= ^obs_r[287:272];
  always @(posedge clk) red[18] <= ^obs_r[291:288];
  reg dout_r;
  always @(posedge clk) dout_r <= ^red;
  assign dout = dout_r;
  VexiiRiscv dut (
    .clk(clk),
    .reset(rst),
    .EmbeddedRiscvJtag_logic_jtagInstruction_tck(EmbeddedRiscvJtag_logic_jtagInstruction_tck),
    .EmbeddedRiscvJtag_logic_jtagInstruction_tdi(stim[0]),
    .EmbeddedRiscvJtag_logic_jtagInstruction_enable(stim[1]),
    .EmbeddedRiscvJtag_logic_jtagInstruction_capture(stim[2]),
    .EmbeddedRiscvJtag_logic_jtagInstruction_shift(stim[3]),
    .EmbeddedRiscvJtag_logic_jtagInstruction_update(stim[4]),
    .EmbeddedRiscvJtag_logic_jtagInstruction_reset(stim[5]),
    .PrivilegedPlugin_logic_rdtime(stim[69:6]),
    .PrivilegedPlugin_logic_harts_0_int_m_timer(stim[70]),
    .PrivilegedPlugin_logic_harts_0_int_m_software(stim[71]),
    .PrivilegedPlugin_logic_harts_0_int_m_external(stim[72]),
    .LsuL1WishbonePlugin_logic_bus_ACK(stim[73]),
    .LsuL1WishbonePlugin_logic_bus_DAT_MISO(stim[137:74]),
    .LsuL1WishbonePlugin_logic_bus_ERR(stim[138]),
    .FetchL1WishbonePlugin_logic_bus_ACK(stim[139]),
    .FetchL1WishbonePlugin_logic_bus_DAT_MISO(stim[171:140]),
    .FetchL1WishbonePlugin_logic_bus_ERR(stim[172]),
    .LsuCachelessWishbonePlugin_logic_bridge_down_ACK(stim[173]),
    .LsuCachelessWishbonePlugin_logic_bridge_down_DAT_MISO(stim[237:174]),
    .LsuCachelessWishbonePlugin_logic_bridge_down_ERR(stim[238]),
    .EmbeddedRiscvJtag_logic_debug_reset(stim[239]),
    .EmbeddedRiscvJtag_logic_jtagInstruction_tdo(obs[0]),
    .EmbeddedRiscvJtag_logic_ndmreset(obs[1]),
    .LsuL1WishbonePlugin_logic_bus_CYC(obs[2]),
    .LsuL1WishbonePlugin_logic_bus_STB(obs[3]),
    .LsuL1WishbonePlugin_logic_bus_WE(obs[4]),
    .LsuL1WishbonePlugin_logic_bus_ADR(obs[33:5]),
    .LsuL1WishbonePlugin_logic_bus_DAT_MOSI(obs[97:34]),
    .LsuL1WishbonePlugin_logic_bus_SEL(obs[105:98]),
    .LsuL1WishbonePlugin_logic_bus_CTI(obs[108:106]),
    .LsuL1WishbonePlugin_logic_bus_BTE(obs[110:109]),
    .FetchL1WishbonePlugin_logic_bus_WE(obs[111]),
    .FetchL1WishbonePlugin_logic_bus_ADR(obs[141:112]),
    .FetchL1WishbonePlugin_logic_bus_DAT_MOSI(obs[173:142]),
    .FetchL1WishbonePlugin_logic_bus_SEL(obs[177:174]),
    .FetchL1WishbonePlugin_logic_bus_CTI(obs[180:178]),
    .FetchL1WishbonePlugin_logic_bus_BTE(obs[182:181]),
    .LsuCachelessWishbonePlugin_logic_bridge_down_CYC(obs[183]),
    .LsuCachelessWishbonePlugin_logic_bridge_down_STB(obs[184]),
    .LsuCachelessWishbonePlugin_logic_bridge_down_WE(obs[185]),
    .LsuCachelessWishbonePlugin_logic_bridge_down_ADR(obs[214:186]),
    .LsuCachelessWishbonePlugin_logic_bridge_down_DAT_MOSI(obs[278:215]),
    .LsuCachelessWishbonePlugin_logic_bridge_down_SEL(obs[286:279]),
    .LsuCachelessWishbonePlugin_logic_bridge_down_CTI(obs[289:287]),
    .LsuCachelessWishbonePlugin_logic_bridge_down_BTE(obs[291:290])
  );
endmodule
